// THE OPENING'S WORDS (owner's order, 2026-10-09) — every line the rebuilt
// opening shows: the lesson chips, Ratchet's letter, repair board, waking
// explanation, pod, Volt Pack and counter; Old Servo; the chapter-one goal
// line. Complete in all five languages. Controls are written as {UP}, {INT},
// {ATK}, {HEAL}, {JUMP} and filled with the player's own binding (ctlFill).
TEXT_LAYERS.push({
  robo: true,
  en: {
    n_ratchet: 'Ratchet', n_servo: 'Old Servo',
    heal_hint: 'Repair ready! Stand still and hold {HEAL} to restore a core.',
    // ---- the lesson chips -------------------------------------------------
    tut_move: 'Move', tut_move_h: 'Walk right toward the light',
    tut_out: 'Leave', tut_out_h: 'The door has been open a long time — walk out',
    tut_jump: 'Jump', tut_jump_h: 'A fallen beam blocks the road — press {JUMP} to hop it',
    tut_gate: 'The city gates', tut_gate_h: 'Stand beneath them and press {UP}',
    tut_workshop_h: 'Follow the gold marker',
    op_booth: "Ratchet's booth", op_booth_h: 'A light is on inside — stand at the door and press {UP}',
    op_note: 'Read the letter', op_note_h: 'A switched-off robot with a letter on him — press {INT}',
    op_drawer: 'Open the drawer', op_drawer_h: 'The letter says his battery is in the drawer — press {INT}',
    op_repair: 'Restore his battery', op_repair_h: 'Press {INT} at Ratchet and wire it back in',
    op_pod: 'Use the pod', op_pod_h: 'Step into the pod and press {INT} — it saves and recharges you',
    op_pack: 'The Volt Pack', op_pack_h: 'Press {INT} at Ratchet — he will explain it',
    op_heal: 'Mend a core', op_heal_h: "The pack's first surge cost you a core — stand still and hold {HEAL}",
    op_atk: 'Strike the winch', op_atk_h: 'The yard winch is jammed across the road — press {ATK} beside it',
    op_burst: 'Volt Burst', op_burst_h: 'Hold {ATK} until you crackle, then let go — the burst stops it',
    op_node: 'The monument', op_node_h: 'Press {INT} at the monument and solve its puzzle — puzzles earn IQ for skills',
    op_go: 'Into the meadow', op_go_h: 'The road east leads to the Scrap Meadows',
    op_back: 'Back outside', op_back_h: 'Stand at the den door and press {UP}',
    // ---- the letter and the repair ---------------------------------------
    op_letter: "Ratchet's letter",
    op_letter1: 'A letter is tucked against his empty battery socket.',
    op_letter2: '“Mother’s song has been infected. My marble slowed the virus, but it cannot stop it. I took my battery out before it could take me.”',
    op_letter3: '“My battery is in the drawer beside this chair. Seat it, connect the positive wire, then the ground, and bridge the relay. If you are reading this, there may still be hope. — R.”',
    op_seat: 'His chest socket is empty. Wire his battery back in.',
    op_awake: 'Ratchet is awake.',
    i_ratchetCell: "Ratchet's battery",
    i_ratchetCelld: 'His own battery, hidden in his drawer. Wire it back into the empty socket in his chest to wake him.',
    i_batt: 'Power Cell', i_battd: 'A charged cell. Seated in a switched-off machine, it wakes them.',
    repair_kicker: 'WORKSHOP · RATCHET', repair_title: 'Bring him back', repair_close: 'Close · saved',
    repair_help: 'Drag a part to its socket, or tap each in turn. Keyboard: arrows and Enter.',
    repair_safe: 'No timer. A wrong connection can always be retried.',
    repair_power: 'Restore power', repair_cell: 'Battery', repair_socket: 'Battery socket',
    repair_positive: '+ wire', repair_negative: '− wire', repair_bridge: 'Bridge',
    repair_plus: '+ terminal', repair_minus: '− terminal', repair_relay: 'Relay',
    repair_step0: 'Place Ratchet’s own battery in the empty socket.',
    repair_step1: 'Connect the amber positive wire to the + terminal.',
    repair_step2: 'Connect the blue ground wire to the − terminal.',
    repair_step3: 'Place the bridge across the relay.',
    repair_step4: 'Circuit complete. Restore power when you are ready.',
    repair_retry: 'That socket does not match. Try the highlighted part again.',
    repair_boot: 'Restoring power…',
    // ---- Ratchet wakes: five short pages ---------------------------------
    op_r1: '…My own battery. You put it back. Thank you, little one — I’m Ratchet.',
    op_r2: 'Mother’s song was infected. This marble on my necklace slowed the virus. It could not stop it.',
    op_r3: 'So I took my battery out before it took me. You were asleep in a recharge cradle — you never heard the broadcast.',
    op_r4: 'Under the meadow lies a big deposit of raw marble. Bring me a piece, and I’ll forge a white sword that cuts the virus out.',
    op_r5: 'One more thing: this spare Power Cell is not for you. It’s for Old Servo, out in the meadow. He switched himself off too. Wake him.',
    op_spare: 'Spare Power Cell',
    op_spared: 'Ratchet’s spare, for Old Servo, the winch-keeper in the meadow. Seat it in him to wake him.',
    op_r_pod: 'This pod saves your progress and recharges you. Use it before you leave.',
    op_saved: 'Progress saved · recharged',
    op_saved_h: 'If you fall, you wake up here.',
    // ---- the Volt Pack ---------------------------------------------------
    op_p1: 'That ring of charge on you fills when your hits land. Right now you have no way to spend it.',
    op_p2: 'My Volt Pack fixes that. With it, hold {HEAL} to mend a core, or hold {ATK} and let go for a Volt Burst.',
    op_p3: 'You will need the burst — claws alone won’t crack raw marble. The pack is yours for good. It costs 12 scrap.',
    op_p4: 'You have no scrap, so take 12 for fixing me. Scrap is the money down here: broken machines leave it behind.',
    op_scrap: '12 Scrap',
    op_scrapd: 'The money down here. Broken machines leave it behind; Ratchet takes it for parts and upgrades.',
    op_s_tag: 'BUY THIS FIRST',
    op_s_pack: 'Volt Pack · permanent',
    op_s_packd: 'Wires healing and the Volt Burst into you. Bought once, yours for good.',
    op_s_refill: 'Volt Refill', op_s_refilld: 'Refills your volts to full.',
    op_s_later: 'After the Volt Pack.',
    s_cell: 'Volt Refill', s_celld: 'Refills your volts to full.',
    i_pack: 'Volt Pack (permanent)',
    i_packd: 'Ratchet’s charger, wired into you for good. Hold {HEAL} to spend volts mending a core. Hold {ATK} and let go to spend them on a Volt Burst.',
    story_pack_first: 'Buy the Volt Pack first.',
    op_r_heal: 'First surge always bites. Stand still and hold {HEAL} — the pack mends it.',
    op_r_winch: 'The yard winch outside has been jammed across the road since the song. Go and stop it — strike, then burst.',
    op_r_node: 'There is a puzzle monument just past the winch. Thinking pays, down here.',
    op_r_go: 'The meadow is east. Old Servo first — then the marble.',
    op_winch_down: 'The winch shudders and stops.',
    // ---- Old Servo -------------------------------------------------------
    op_sv_dark: 'Old Servo sits dark in his winding drum. He is switched off — a Power Cell would wake him.',
    op_sv_seat: 'Ratchet’s spare cell fits the port in his chest. You seat it.',
    op_sv_woke: 'Old Servo is awake.',
    op_sv1: 'Mrrow… power! A working unit — and a cat, no less. I’m Old Servo, keeper of this winding house. Tell Ratchet thank you.',
    op_sv2: 'After his marble? It’s under us. The hub east of here has a loose floor at its west end — break through it and the caves open up.',
    op_sv3: 'And a favour, if you have legs for it: my gantry coil shook loose up in the gantries. The climb starts right behind me. Bring it back and I’ll pay you 60 scrap and 10 IQ.',
    op_sv_cue_dark: 'Switched off · needs a Power Cell',
    op_sv_cue_wake: '{INT} — wake Old Servo',
    q_where_servo_coil: 'The coil is up in the gantries — the climb starts right behind me.',
    q_thanks_servo_coil: 'That’s my coil! Listen — the drum turns true again. Here: 60 scrap and 10 IQ, as promised.',
    d_servo: [
      'Hear that? The drum turns true. Every gantry over this meadow hangs straight again.',
      'Mind the hub’s loose floor, little paw. It’s the way down to the marble.'
    ],
    // ---- the goal line ---------------------------------------------------
    op_o_gate: 'Reach the city gates',
    op_o_booth: 'Find who is still awake — Ratchet’s booth',
    op_o_wake: 'Wake Ratchet',
    op_o_pod: 'Use Ratchet’s pod',
    op_o_pack: 'Get the Volt Pack from Ratchet',
    op_o_lessons: 'Try out the Volt Pack',
    op_o_node: 'Solve the monument’s puzzle',
    op_o_meadow: 'Head east into the Scrap Meadows',
    op_o_marble: 'Find the raw marble beneath the meadow',
    op_o_return: 'Bring the raw marble to Ratchet',
    op_o_sage: 'Free the first sage — the door beside the marble quarry',
    op_o_chime: 'Silence the bell on the climb above the meadow',
    op_o_lion: 'Free NULLFANG in his enclosure past the camp',
    op_o_conduits: 'Climb to the Data Conduits above the camp',
  },
  ar: {
    n_ratchet: 'راتشيت', n_servo: 'سيرفو العجوز',
    heal_hint: 'الإصلاح جاهز! قفي ساكنة واضغطي مطوّلًا على {HEAL} لاستعادة نواة.',
    tut_move: 'التحرّك', tut_move_h: 'امشي يمينًا نحو الضوء',
    tut_out: 'اخرجي', tut_out_h: 'البابُ مفتوحٌ منذ زمنٍ طويل — اخرجي منه',
    tut_jump: 'القفز', tut_jump_h: 'عارضة ساقطة تسدّ الطريق — اضغطي {JUMP} لتقفزي فوقها',
    tut_gate: 'بوّابات المدينة', tut_gate_h: 'قفي تحتها واضغطي {UP}',
    tut_workshop_h: 'اتبعي العلامة الذهبية',
    op_booth: 'كشك راتشيت', op_booth_h: 'في الداخل ضوء — قفي عند الباب واضغطي {UP}',
    op_note: 'اقرئي الرسالة', op_note_h: 'روبوت مُطفأ عليه رسالة — اضغطي {INT}',
    op_drawer: 'افتحي الدُّرج', op_drawer_h: 'تقول الرسالة إن بطاريته في الدُّرج — اضغطي {INT}',
    op_repair: 'أعيدي بطاريته', op_repair_h: 'اضغطي {INT} عند راتشيت وأعيدي توصيلها',
    op_pod: 'استخدمي الحجرة', op_pod_h: 'ادخلي الحجرة واضغطي {INT} — تحفظ تقدّمك وتعيد شحنك',
    op_pack: 'حزمة الفولت', op_pack_h: 'اضغطي {INT} عند راتشيت — سيشرحها لك',
    op_heal: 'أصلحي نواة', op_heal_h: 'الدفقة الأولى للحزمة كلّفتك نواة — قفي ساكنة واضغطي مطوّلًا على {HEAL}',
    op_atk: 'اضربي الرافعة', op_atk_h: 'رافعة الساحة عالقة عبر الطريق — اضغطي {ATK} بجانبها',
    op_burst: 'انفجار الفولت', op_burst_h: 'اضغطي مطوّلًا على {ATK} حتى تتطاير الشرارات منك، ثم أفلتي — الانفجار يوقفها',
    op_node: 'النُّصب', op_node_h: 'اضغطي {INT} عند النُّصب وحُلّي لغزه — الألغاز تمنح ذكاءً للمهارات',
    op_go: 'إلى المرج', op_go_h: 'الطريق شرقًا يقود إلى مروج الخردة',
    op_back: 'إلى الخارج', op_back_h: 'قفي عند باب الورشة واضغطي {UP}',
    op_letter: 'رسالة راتشيت',
    op_letter1: 'رسالة موضوعة بجوار موضع بطاريته الفارغ.',
    op_letter2: '«لقد أُصيبت أغنية الأم بالعدوى. أبطأ رخامي الفيروس، لكنه لا يستطيع إيقافه. نزعتُ بطاريتي قبل أن يستولي عليّ.»',
    op_letter3: '«بطاريتي في الدُّرج بجانب هذا الكرسي. ثبّتيها، ثم صِلي السلك الموجب، ثم الأرضي، وجسّري المُرحِّل. إن كنتِ تقرئين هذا، فربما ما زال هناك أمل. — ر.»',
    op_seat: 'موضع البطارية في صدره فارغ. أعيدي توصيل بطاريته.',
    op_awake: 'استيقظ راتشيت.',
    i_ratchetCell: 'بطارية راتشيت',
    i_ratchetCelld: 'بطاريته هو، مخبّأة في دُرجه. أعيدي توصيلها في الموضع الفارغ في صدره لتوقظيه.',
    i_batt: 'خلية طاقة', i_battd: 'خلية مشحونة. إذا ثُبّتت في آلة مُطفأة أيقظتها.',
    repair_kicker: 'الورشة · راتشيت', repair_title: 'أعيديه إلى الحياة', repair_close: 'إغلاق · محفوظ',
    repair_help: 'اسحبي كل قطعة إلى موضعها، أو المسيها بالترتيب. لوحة المفاتيح: الأسهم وEnter.',
    repair_safe: 'لا مؤقّت. يمكن دائمًا إعادة المحاولة بعد توصيل خاطئ.',
    repair_power: 'أعيدي الطاقة', repair_cell: 'البطارية', repair_socket: 'موضع البطارية',
    repair_positive: 'السلك +', repair_negative: 'السلك −', repair_bridge: 'الجسر',
    repair_plus: 'الطرف +', repair_minus: 'الطرف −', repair_relay: 'المُرحِّل',
    repair_step0: 'ضعي بطارية راتشيت نفسه في الموضع الفارغ.',
    repair_step1: 'صِلي السلك الموجب الكهرماني بالطرف +.',
    repair_step2: 'صِلي السلك الأرضي الأزرق بالطرف −.',
    repair_step3: 'ضعي الجسر عبر المُرحِّل.',
    repair_step4: 'اكتملت الدائرة. أعيدي الطاقة حين تكونين مستعدة.',
    repair_retry: 'هذا الموضع غير مطابق. جرّبي القطعة المضيئة مرة أخرى.',
    repair_boot: 'جارٍ إعادة الطاقة…',
    op_r1: '…بطاريتي أنا. أعدتِها. شكرًا لكِ يا صغيرة — أنا راتشيت.',
    op_r2: 'أُصيبت أغنية الأم بالعدوى. هذا الرخام في قلادتي أبطأ الفيروس، لكنه لم يستطع إيقافه.',
    op_r3: 'فنزعتُ بطاريتي قبل أن يستولي عليّ. كنتِ نائمة في مهد الشحن — لم تسمعي البثّ أصلًا.',
    op_r4: 'تحت المرج ترسّب كبير من الرخام الخام. أحضري لي قطعة، وسأصوغ منها سيفًا أبيض يقطع الفيروس.',
    op_r5: 'وأمر آخر: خلية الطاقة الاحتياطية هذه ليست لكِ. إنها لسيرفو العجوز في المرج. أطفأ نفسه هو أيضًا. أيقظيه.',
    op_spare: 'خلية طاقة احتياطية',
    op_spared: 'احتياطي راتشيت، لسيرفو العجوز حارس الرافعة في المرج. ثبّتيها فيه لتوقظيه.',
    op_r_pod: 'هذه الحجرة تحفظ تقدّمك وتعيد شحنك. استخدميها قبل أن تغادري.',
    op_saved: 'تم حفظ التقدّم · أُعيد الشحن',
    op_saved_h: 'إن سقطتِ، تستيقظين هنا.',
    op_p1: 'حلقة الشحنة التي عليكِ تمتلئ حين تصيب ضرباتك. الآن لا سبيل لكِ إلى إنفاقها.',
    op_p2: 'حزمة الفولت خاصتي تصلح ذلك. معها اضغطي مطوّلًا على {HEAL} لإصلاح نواة، أو اضغطي مطوّلًا على {ATK} ثم أفلتي لانفجار الفولت.',
    op_p3: 'ستحتاجين الانفجار — المخالب وحدها لا تكسر الرخام الخام. الحزمة لكِ إلى الأبد، وثمنها 12 خردة.',
    op_p4: 'ليس معكِ خردة، فخذي 12 أجرةَ إصلاحي. الخردة هي المال هنا: الآلات المكسورة تتركها خلفها.',
    op_scrap: '12 خردة',
    op_scrapd: 'المال هنا. الآلات المكسورة تتركها خلفها، وراتشيت يأخذها ثمنًا للقطع والترقيات.',
    op_s_tag: 'اشتري هذا أولًا',
    op_s_pack: 'حزمة الفولت · دائمة',
    op_s_packd: 'توصل العلاج وانفجار الفولت بكِ. تُشترى مرة واحدة وتبقى لكِ.',
    op_s_refill: 'إعادة تعبئة الفولت', op_s_refilld: 'تملأ فولتاتك حتى آخرها.',
    op_s_later: 'بعد حزمة الفولت.',
    s_cell: 'إعادة تعبئة الفولت', s_celld: 'تملأ فولتاتك حتى آخرها.',
    i_pack: 'حزمة الفولت (دائمة)',
    i_packd: 'شاحن راتشيت، موصول بكِ إلى الأبد. اضغطي مطوّلًا على {HEAL} لإنفاق الفولت في إصلاح نواة، واضغطي مطوّلًا على {ATK} ثم أفلتي لإنفاقه في انفجار الفولت.',
    story_pack_first: 'اشتري حزمة الفولت أولًا.',
    op_r_heal: 'الدفقة الأولى تلسع دائمًا. قفي ساكنة واضغطي مطوّلًا على {HEAL} — الحزمة تصلحها.',
    op_r_winch: 'رافعة الساحة في الخارج عالقة عبر الطريق منذ الأغنية. اذهبي وأوقفيها — اضربي، ثم فجّري.',
    op_r_node: 'بعد الرافعة مباشرة نُصب فيه لغز. التفكير يُثمر هنا في الأسفل.',
    op_r_go: 'المرج شرقًا. سيرفو العجوز أولًا — ثم الرخام.',
    op_winch_down: 'ترتجف الرافعة وتتوقف.',
    op_sv_dark: 'يجلس سيرفو العجوز مُطفأً في أسطوانة الرافعة. إنه مُطفأ — خلية طاقة ستوقظه.',
    op_sv_seat: 'خلية راتشيت الاحتياطية تناسب المنفذ في صدره. تثبّتينها.',
    op_sv_woke: 'استيقظ سيرفو العجوز.',
    op_sv1: 'مياو… طاقة! وحدة تعمل — وقطة أيضًا. أنا سيرفو العجوز، حارس بيت الرافعة هذا. اشكري راتشيت عنّي.',
    op_sv2: 'تبحثين عن رخامه؟ إنه تحتنا. في الساحة شرق هنا أرضية متخلخلة عند طرفها الغربي — اكسريها فتنفتح الكهوف.',
    op_sv3: 'ومعروف إن كانت لكِ أرجل له: انفكّ ملف الرافعة خاصتي هناك في الأعلى بين الجسور. التسلّق يبدأ خلفي مباشرة. أعيديه وسأدفع لكِ 60 خردة و10 ذكاء.',
    op_sv_cue_dark: 'مُطفأ · يحتاج خلية طاقة',
    op_sv_cue_wake: '{INT} — أيقظي سيرفو العجوز',
    q_where_servo_coil: 'الملف في الأعلى بين الجسور — التسلّق يبدأ خلفي مباشرة.',
    q_thanks_servo_coil: 'هذا ملفّي! اسمعي — الأسطوانة تدور مستقيمة من جديد. تفضّلي: 60 خردة و10 ذكاء، كما وعدت.',
    d_servo: [
      'أتسمعين؟ الأسطوانة تدور مستقيمة. كل جسر فوق هذا المرج معلّق مستقيمًا من جديد.',
      'انتبهي لأرضية الساحة المتخلخلة يا صغيرة. إنها الطريق إلى الرخام.'
    ],
    op_o_gate: 'اذهبي إلى بوّابات المدينة',
    op_o_booth: 'ابحثي عمّن ما زال مستيقظًا — كشك راتشيت',
    op_o_wake: 'أيقظي راتشيت',
    op_o_pod: 'استخدمي حجرة راتشيت',
    op_o_pack: 'احصلي على حزمة الفولت من راتشيت',
    op_o_lessons: 'جرّبي حزمة الفولت',
    op_o_node: 'حُلّي لغز النُّصب',
    op_o_meadow: 'اتجهي شرقًا إلى مروج الخردة',
    op_o_marble: 'اعثري على الرخام الخام تحت المرج',
    op_o_return: 'أحضري الرخام الخام إلى راتشيت',
    op_o_sage: 'حرّري الحكيم الأول — الباب بجانب محجر الرخام',
    op_o_chime: 'أسكتي الجرس على التسلّق فوق المرج',
    op_o_lion: 'حرّري نَلفانغ في حظيرته بعد المخيّم',
    op_o_conduits: 'تسلّقي إلى قنوات البيانات فوق المخيّم',
  },
  tr: {
    n_ratchet: 'Ratchet', n_servo: 'Yaşlı Servo',
    heal_hint: 'Onarım hazır! Kımıldama ve bir çekirdeği geri kazanmak için {HEAL} tuşunu basılı tut.',
    tut_move: 'Hareket', tut_move_h: 'Sağa, ışığa doğru yürü',
    tut_out: 'Çık', tut_out_h: 'Kapı uzun zamandır açık — dışarı yürü',
    tut_jump: 'Zıpla', tut_jump_h: 'Devrilmiş bir kiriş yolu kapatıyor — üstünden atlamak için {JUMP}',
    tut_gate: 'Şehir kapıları', tut_gate_h: 'Altlarında dur ve {UP} tuşuna bas',
    tut_workshop_h: 'Altın işareti izle',
    op_booth: "Ratchet'in kulübesi", op_booth_h: 'İçeride ışık yanıyor — kapıda dur ve {UP} tuşuna bas',
    op_note: 'Mektubu oku', op_note_h: 'Üstünde mektup olan kapalı bir robot — {INT} tuşuna bas',
    op_drawer: 'Çekmeceyi aç', op_drawer_h: 'Mektuba göre bataryası çekmecede — {INT} tuşuna bas',
    op_repair: 'Bataryasını tak', op_repair_h: "Ratchet'in yanında {INT} tuşuna bas ve bataryayı yeniden bağla",
    op_pod: 'Kabini kullan', op_pod_h: 'Kabine gir ve {INT} tuşuna bas — ilerlemeni kaydeder, seni şarj eder',
    op_pack: 'Volt Paketi', op_pack_h: "Ratchet'in yanında {INT} tuşuna bas — sana anlatacak",
    op_heal: 'Bir çekirdek onar', op_heal_h: "Paketin ilk dalgası sana bir çekirdeğe mal oldu — kımıldama ve {HEAL} tuşunu basılı tut",
    op_atk: 'Vinci vur', op_atk_h: 'Avlu vinci yolun karşısında sıkışmış — yanında {ATK} tuşuna bas',
    op_burst: 'Volt Patlaması', op_burst_h: '{ATK} tuşunu çatırdayana kadar basılı tut, sonra bırak — patlama onu durdurur',
    op_node: 'Anıt', op_node_h: 'Anıtta {INT} tuşuna bas ve bulmacasını çöz — bulmacalar beceriler için IQ kazandırır',
    op_go: 'Çayıra', op_go_h: 'Doğudaki yol Hurda Çayırlarına çıkar',
    op_back: 'Dışarı', op_back_h: 'Atölye kapısında dur ve {UP} tuşuna bas',
    op_letter: "Ratchet'in mektubu",
    op_letter1: 'Boş batarya yuvasının yanına bir mektup sıkıştırılmış.',
    op_letter2: '“Ana’nın şarkısına virüs bulaştı. Mermerim virüsü yavaşlattı ama durduramıyor. Beni ele geçirmeden önce bataryamı çıkardım.”',
    op_letter3: '“Bataryam bu sandalyenin yanındaki çekmecede. Yerine oturt, önce artı kabloyu, sonra topraklamayı bağla ve röleye köprü kur. Bunu okuyorsan belki hâlâ umut vardır. — R.”',
    op_seat: 'Göğsündeki yuva boş. Bataryasını yeniden bağla.',
    op_awake: 'Ratchet uyandı.',
    i_ratchetCell: "Ratchet'in bataryası",
    i_ratchetCelld: 'Kendi bataryası, çekmecesine saklanmış. Onu uyandırmak için göğsündeki boş yuvaya yeniden bağla.',
    i_batt: 'Güç Hücresi', i_battd: 'Şarjlı bir hücre. Kapalı bir makineye takılınca onu uyandırır.',
    repair_kicker: 'ATÖLYE · RATCHET', repair_title: 'Onu geri getir', repair_close: 'Kapat · kaydedildi',
    repair_help: 'Her parçayı yuvasına sürükle ya da sırayla dokun. Klavye: oklar ve Enter.',
    repair_safe: 'Süre yok. Yanlış bağlantı her zaman yeniden denenebilir.',
    repair_power: 'Gücü ver', repair_cell: 'Batarya', repair_socket: 'Batarya yuvası',
    repair_positive: '+ kablo', repair_negative: '− kablo', repair_bridge: 'Köprü',
    repair_plus: '+ uç', repair_minus: '− uç', repair_relay: 'Röle',
    repair_step0: "Ratchet'in kendi bataryasını boş yuvaya yerleştir.",
    repair_step1: 'Kehribar renkli artı kabloyu + uca bağla.',
    repair_step2: 'Mavi topraklama kablosunu − uca bağla.',
    repair_step3: 'Köprüyü rölenin üstüne yerleştir.',
    repair_step4: 'Devre tamam. Hazır olduğunda gücü ver.',
    repair_retry: 'Bu yuva uymuyor. Vurgulanan parçayı yeniden dene.',
    repair_boot: 'Güç veriliyor…',
    op_r1: '…Kendi bataryam. Yerine taktın. Teşekkürler, küçüğüm — ben Ratchet.',
    op_r2: 'Ana’nın şarkısına virüs bulaştı. Kolyemdeki bu mermer virüsü yavaşlattı. Durduramadı.',
    op_r3: 'Ben de beni ele geçirmeden bataryamı çıkardım. Sen bir şarj beşiğinde uyuyordun — yayını hiç duymadın.',
    op_r4: 'Çayırın altında büyük bir ham mermer yatağı var. Bana bir parça getir, virüsü kesip atan beyaz bir kılıç döveyim.',
    op_r5: 'Bir şey daha: bu yedek Güç Hücresi senin için değil. Çayırdaki Yaşlı Servo için. O da kendini kapattı. Onu uyandır.',
    op_spare: 'Yedek Güç Hücresi',
    op_spared: "Ratchet'in yedeği, çayırdaki vinç bekçisi Yaşlı Servo için. Onu uyandırmak için ona tak.",
    op_r_pod: 'Bu kabin ilerlemeni kaydeder ve seni şarj eder. Gitmeden önce kullan.',
    op_saved: 'İlerleme kaydedildi · şarj edildi',
    op_saved_h: 'Düşersen burada uyanırsın.',
    op_p1: 'Üstündeki şarj halkası vuruşların isabet ettikçe dolar. Şu an onu harcamanın bir yolu yok.',
    op_p2: 'Volt Paketim bunu çözer. Onunla bir çekirdek onarmak için {HEAL} tuşunu basılı tut, ya da {ATK} tuşunu basılı tutup bırak: Volt Patlaması.',
    op_p3: 'Patlamaya ihtiyacın olacak — pençeler tek başına ham mermeri kıramaz. Paket artık hep senin. Fiyatı 12 hurda.',
    op_p4: 'Hiç hurdan yok; beni onardığın için şu 12’yi al. Hurda buranın parası: kırık makineler onu geride bırakır.',
    op_scrap: '12 Hurda',
    op_scrapd: 'Buranın parası. Kırık makineler onu geride bırakır; Ratchet parça ve yükseltme karşılığında alır.',
    op_s_tag: 'ÖNCE BUNU AL',
    op_s_pack: 'Volt Paketi · kalıcı',
    op_s_packd: 'İyileşmeyi ve Volt Patlamasını sana bağlar. Bir kez alınır, hep senindir.',
    op_s_refill: 'Volt Dolumu', op_s_refilld: 'Voltlarını tamamen doldurur.',
    op_s_later: 'Volt Paketinden sonra.',
    s_cell: 'Volt Dolumu', s_celld: 'Voltlarını tamamen doldurur.',
    i_pack: 'Volt Paketi (kalıcı)',
    i_packd: "Ratchet'in şarj cihazı, kalıcı olarak sana bağlandı. Voltları bir çekirdek onarmaya harcamak için {HEAL} tuşunu basılı tut. Volt Patlamasına harcamak için {ATK} tuşunu basılı tutup bırak.",
    story_pack_first: 'Önce Volt Paketini al.',
    op_r_heal: 'İlk dalga hep acıtır. Kımıldama ve {HEAL} tuşunu basılı tut — paket onarır.',
    op_r_winch: 'Dışarıdaki avlu vinci şarkıdan beri yolun karşısında sıkışık. Git, durdur onu — önce vur, sonra patlat.',
    op_r_node: 'Vincin hemen ötesinde bulmacalı bir anıt var. Burada düşünmek kazandırır.',
    op_r_go: 'Çayır doğuda. Önce Yaşlı Servo — sonra mermer.',
    op_winch_down: 'Vinç sarsılır ve durur.',
    op_sv_dark: 'Yaşlı Servo vinç tamburunun içinde kapalı oturuyor. Kendini kapatmış — bir Güç Hücresi onu uyandırır.',
    op_sv_seat: "Ratchet'in yedek hücresi göğsündeki girişe uyuyor. Yerine takıyorsun.",
    op_sv_woke: 'Yaşlı Servo uyandı.',
    op_sv1: "Mrrr… güç! Çalışan bir birim — üstelik bir kedi. Ben Yaşlı Servo, bu vinç evinin bekçisi. Ratchet'e teşekkürümü ilet.",
    op_sv2: 'Mermerini mi arıyorsun? Altımızda. Doğudaki meydanın batı ucunda gevşek bir zemin var — onu kır, mağaralar açılır.',
    op_sv3: 'Bir de ricam var, bacakların yeterse: vinç bobinim yukarıda, iskelelerin arasında gevşeyip düştü. Tırmanış tam arkamda başlıyor. Getirirsen sana 60 hurda ve 10 IQ veririm.',
    op_sv_cue_dark: 'Kapalı · Güç Hücresi gerekli',
    op_sv_cue_wake: "{INT} — Yaşlı Servo'yu uyandır",
    q_where_servo_coil: 'Bobin yukarıda, iskelelerin arasında — tırmanış tam arkamda başlıyor.',
    q_thanks_servo_coil: 'Bu benim bobinim! Dinle — tambur yine düzgün dönüyor. Al: söz verdiğim gibi 60 hurda ve 10 IQ.',
    d_servo: [
      'Duyuyor musun? Tambur düzgün dönüyor. Bu çayırın üstündeki her iskele yine dümdüz asılı.',
      'Meydandaki gevşek zemine dikkat et, minik pati. Mermere inen yol o.'
    ],
    op_o_gate: 'Şehir kapılarına ulaş',
    op_o_booth: "Hâlâ uyanık olanı bul — Ratchet'in kulübesi",
    op_o_wake: "Ratchet'i uyandır",
    op_o_pod: "Ratchet'in kabinini kullan",
    op_o_pack: "Ratchet'ten Volt Paketini al",
    op_o_lessons: 'Volt Paketini dene',
    op_o_node: 'Anıtın bulmacasını çöz',
    op_o_meadow: 'Doğuya, Hurda Çayırlarına git',
    op_o_marble: 'Çayırın altındaki ham mermeri bul',
    op_o_return: "Ham mermeri Ratchet'e götür",
    op_o_sage: 'İlk bilgeyi özgür bırak — mermer ocağının yanındaki kapı',
    op_o_chime: 'Çayırın üstündeki tırmanışta çanı sustur',
    op_o_lion: "Kampın ötesindeki ağılında NULLFANG'i özgür bırak",
    op_o_conduits: 'Kampın üstündeki Veri Kanallarına tırman',
  },
  zh: {
    n_ratchet: '拉切特', n_servo: '老伺服',
    heal_hint: '维修就绪！站稳并按住 {HEAL} 来恢复一颗核心。',
    tut_move: '移动', tut_move_h: '向右走，朝着光',
    tut_out: '离开', tut_out_h: '门早就开着——走出去',
    tut_jump: '跳跃', tut_jump_h: '倒下的横梁挡住了路——按 {JUMP} 跳过去',
    tut_gate: '城门', tut_gate_h: '站到城门下，按 {UP}',
    tut_workshop_h: '跟着金色标记走',
    op_booth: '拉切特的小铺', op_booth_h: '里面亮着灯——站在门口，按 {UP}',
    op_note: '读那封信', op_note_h: '一个关了机的机器人，身上有封信——按 {INT}',
    op_drawer: '打开抽屉', op_drawer_h: '信上说他的电池在抽屉里——按 {INT}',
    op_repair: '装回他的电池', op_repair_h: '在拉切特面前按 {INT}，把电池接回去',
    op_pod: '使用休眠舱', op_pod_h: '走进舱里按 {INT}——它会保存进度并为你充能',
    op_pack: '伏特包', op_pack_h: '在拉切特面前按 {INT}——他会讲给你听',
    op_heal: '修复一颗核心', op_heal_h: '伏特包的第一次涌流让你掉了一颗核心——站稳，按住 {HEAL}',
    op_atk: '攻击绞车', op_atk_h: '院子里的绞车卡在路中间——走到旁边按 {ATK}',
    op_burst: '伏特爆发', op_burst_h: '按住 {ATK} 直到全身噼啪作响，然后松开——爆发能让它停下',
    op_node: '石碑', op_node_h: '在石碑前按 {INT} 并解开谜题——谜题能赚取用于技能的智商',
    op_go: '前往草原', op_go_h: '往东的路通向废料草原',
    op_back: '回到外面', op_back_h: '站到工坊门口，按 {UP}',
    op_letter: '拉切特的信',
    op_letter1: '一封信塞在他空着的电池槽旁。',
    op_letter2: '“母亲的歌被感染了。我的大理石减缓了病毒，却挡不住它。在它控制我之前，我把自己的电池取了出来。”',
    op_letter3: '“我的电池在这把椅子旁的抽屉里。把它装好，先接正极线，再接地线，然后在继电器上搭好桥。如果你读到了这封信，也许还有希望。——R.”',
    op_seat: '他胸口的电池槽是空的。把他的电池接回去。',
    op_awake: '拉切特醒了。',
    i_ratchetCell: '拉切特的电池',
    i_ratchetCelld: '他自己的电池，藏在抽屉里。把它接回他胸口的空槽，就能唤醒他。',
    i_batt: '能量电池', i_battd: '一枚充满电的电池。装进关机的机器里，就能把它唤醒。',
    repair_kicker: '工坊 · 拉切特', repair_title: '让他回来', repair_close: '关闭 · 已保存',
    repair_help: '把每个零件拖到它的插槽，或依次点击。键盘：方向键和回车。',
    repair_safe: '没有时间限制。接错了随时可以重来。',
    repair_power: '恢复供电', repair_cell: '电池', repair_socket: '电池槽',
    repair_positive: '+ 导线', repair_negative: '− 导线', repair_bridge: '跨接片',
    repair_plus: '+ 端子', repair_minus: '− 端子', repair_relay: '继电器',
    repair_step0: '把拉切特自己的电池放进空槽。',
    repair_step1: '把琥珀色的正极线接到 + 端子。',
    repair_step2: '把蓝色的地线接到 − 端子。',
    repair_step3: '把跨接片搭在继电器上。',
    repair_step4: '电路已接通。准备好就恢复供电。',
    repair_retry: '这个插槽不对。再试一次高亮的零件。',
    repair_boot: '正在恢复供电……',
    op_r1: '……我自己的电池。你把它装回来了。谢谢你，小家伙——我叫拉切特。',
    op_r2: '母亲的歌被感染了。我项链上这块大理石减缓了病毒，却没能挡住它。',
    op_r3: '所以在它控制我之前，我取出了自己的电池。你那时在充电摇篮里睡着——根本没听到那次广播。',
    op_r4: '草原底下有一大片原生大理石矿。给我带一块回来，我能锻造一把把病毒斩除的白剑。',
    op_r5: '还有一件事：这枚备用能量电池不是给你的，是给草原上的老伺服的。他也把自己关了机。去唤醒他。',
    op_spare: '备用能量电池',
    op_spared: '拉切特的备用电池，留给草原上看守绞车的老伺服。装进他体内，就能唤醒他。',
    op_r_pod: '这个舱会保存你的进度，并给你充能。走之前用一下。',
    op_saved: '进度已保存 · 已充能',
    op_saved_h: '如果你倒下，会在这里醒来。',
    op_p1: '你身上那圈电量会在攻击命中时充满。可现在你没办法用它。',
    op_p2: '我的伏特包能解决这个。装上它，按住 {HEAL} 修复一颗核心，或者按住 {ATK} 再松开，放出伏特爆发。',
    op_p3: '你会需要爆发——光靠爪子劈不开原生大理石。伏特包永久归你，价格是 12 废料。',
    op_p4: '你身上没有废料，这 12 个就当是修好我的报酬。废料是这里的钱：坏掉的机器会留下它。',
    op_scrap: '12 废料',
    op_scrapd: '这里的钱。坏掉的机器会留下它；拉切特收它来换零件和升级。',
    op_s_tag: '先买这个',
    op_s_pack: '伏特包 · 永久',
    op_s_packd: '把治疗和伏特爆发接入你体内。只需购买一次，永久归你。',
    op_s_refill: '伏特补充', op_s_refilld: '把你的伏特充满。',
    op_s_later: '买了伏特包之后。',
    s_cell: '伏特补充', s_celld: '把你的伏特充满。',
    i_pack: '伏特包（永久）',
    i_packd: '拉切特的充电器，永久接入你体内。按住 {HEAL}，用伏特修复核心。按住 {ATK} 再松开，用伏特放出伏特爆发。',
    story_pack_first: '先买伏特包。',
    op_r_heal: '第一次涌流总会咬人一口。站稳，按住 {HEAL}——伏特包会修好它。',
    op_r_winch: '外面院子里的绞车自从那首歌之后就卡在路中间。去让它停下——先打，再爆发。',
    op_r_node: '绞车过去不远有座谜题石碑。在这下面，动脑子是有回报的。',
    op_r_go: '草原在东边。先找老伺服——然后去找大理石。',
    op_winch_down: '绞车一阵抖动，停了下来。',
    op_sv_dark: '老伺服坐在他的绞盘里，一片漆黑。他关了机——一枚能量电池就能唤醒他。',
    op_sv_seat: '拉切特的备用电池正好插进他胸口的接口。你把它装了进去。',
    op_sv_woke: '老伺服醒了。',
    op_sv1: '喵呜……有电了！一台能动的机器——还是只猫。我是老伺服，这座绞车房的看守。替我谢谢拉切特。',
    op_sv2: '在找他的大理石？就在我们脚下。东边枢纽的西头有块松动的地面——打穿它，洞穴就露出来了。',
    op_sv3: '还有个忙，要是你腿脚利索的话：我的吊架线圈在上面的吊架间松脱了。攀爬的路就在我身后。拿回来，我付你 60 废料和 10 智商。',
    op_sv_cue_dark: '已关机 · 需要能量电池',
    op_sv_cue_wake: '{INT} — 唤醒老伺服',
    q_where_servo_coil: '线圈在上面的吊架之间——攀爬的路就在我身后。',
    q_thanks_servo_coil: '这就是我的线圈！听——绞盘又转得稳稳的了。给：说好的 60 废料和 10 智商。',
    d_servo: [
      '听见了吗？绞盘转得稳稳的。这片草原上的每座吊架又挂得笔直了。',
      '小心枢纽那块松动的地面，小爪子。那就是通往大理石的路。'
    ],
    op_o_gate: '前往城门',
    op_o_booth: '去找还醒着的人——拉切特的小铺',
    op_o_wake: '唤醒拉切特',
    op_o_pod: '使用拉切特的休眠舱',
    op_o_pack: '从拉切特那里获得伏特包',
    op_o_lessons: '试试伏特包',
    op_o_node: '解开石碑的谜题',
    op_o_meadow: '往东前往废料草原',
    op_o_marble: '找到草原底下的原生大理石',
    op_o_return: '把原生大理石带给拉切特',
    op_o_sage: '解放第一位贤者——大理石采石场旁的门',
    op_o_chime: '让草原上方攀登处的钟沉默',
    op_o_lion: '在营地后的围栏里解放 NULLFANG',
    op_o_conduits: '爬上营地上方的数据导管',
  },
  ru: {
    n_ratchet: 'Рэтчет', n_servo: 'Старый Серво',
    heal_hint: 'Ремонт готов! Стой на месте и держи {HEAL}, чтобы восстановить ядро.',
    tut_move: 'Движение', tut_move_h: 'Иди вправо, к свету',
    tut_out: 'Выход', tut_out_h: 'Дверь давно открыта — выходи',
    tut_jump: 'Прыжок', tut_jump_h: 'Дорогу перегородила упавшая балка — нажми {JUMP}, чтобы перепрыгнуть',
    tut_gate: 'Ворота города', tut_gate_h: 'Встань под ними и нажми {UP}',
    tut_workshop_h: 'Иди за золотой меткой',
    op_booth: 'Будка Рэтчета', op_booth_h: 'Внутри горит свет — встань у двери и нажми {UP}',
    op_note: 'Прочти письмо', op_note_h: 'Выключенный робот с письмом — нажми {INT}',
    op_drawer: 'Открой ящик', op_drawer_h: 'В письме сказано, что его батарея в ящике — нажми {INT}',
    op_repair: 'Верни ему батарею', op_repair_h: 'Нажми {INT} у Рэтчета и подключи батарею обратно',
    op_pod: 'Капсула', op_pod_h: 'Встань в капсулу и нажми {INT} — она сохранит прогресс и зарядит тебя',
    op_pack: 'Вольт-пак', op_pack_h: 'Нажми {INT} у Рэтчета — он всё объяснит',
    op_heal: 'Почини ядро', op_heal_h: 'Первый разряд пака стоил тебе ядра — стой на месте и держи {HEAL}',
    op_atk: 'Ударь лебёдку', op_atk_h: 'Дворовая лебёдка заклинила поперёк дороги — нажми {ATK} рядом с ней',
    op_burst: 'Вольт-взрыв', op_burst_h: 'Держи {ATK}, пока не затрещат искры, затем отпусти — взрыв её остановит',
    op_node: 'Монумент', op_node_h: 'Нажми {INT} у монумента и реши его головоломку — головоломки дают IQ для навыков',
    op_go: 'На луг', op_go_h: 'Дорога на восток ведёт к Лугам Лома',
    op_back: 'Наружу', op_back_h: 'Встань у двери мастерской и нажми {UP}',
    op_letter: 'Письмо Рэтчета',
    op_letter1: 'К пустому гнезду его батареи приткнуто письмо.',
    op_letter2: '«Песнь Матери заражена. Мой мрамор замедлил вирус, но остановить его не может. Я вынул свою батарею, пока он не овладел мной.»',
    op_letter3: '«Моя батарея в ящике возле этого кресла. Вставь её, подключи плюсовой провод, потом заземление и замкни реле перемычкой. Если ты это читаешь, возможно, надежда ещё есть. — Р.»',
    op_seat: 'Гнездо в его груди пустое. Подключи его батарею обратно.',
    op_awake: 'Рэтчет очнулся.',
    i_ratchetCell: 'Батарея Рэтчета',
    i_ratchetCelld: 'Его собственная батарея, спрятанная в ящике. Подключи её к пустому гнезду в его груди, чтобы разбудить его.',
    i_batt: 'Энергоячейка', i_battd: 'Заряженная ячейка. Вставленная в выключенную машину, она будит её.',
    repair_kicker: 'МАСТЕРСКАЯ · РЭТЧЕТ', repair_title: 'Верни его', repair_close: 'Закрыть · сохранено',
    repair_help: 'Перетащи каждую деталь в её гнездо или нажимай по очереди. Клавиатура: стрелки и Enter.',
    repair_safe: 'Таймера нет. Неверное подключение всегда можно переделать.',
    repair_power: 'Подать питание', repair_cell: 'Батарея', repair_socket: 'Гнездо батареи',
    repair_positive: 'Провод +', repair_negative: 'Провод −', repair_bridge: 'Перемычка',
    repair_plus: 'Клемма +', repair_minus: 'Клемма −', repair_relay: 'Реле',
    repair_step0: 'Вставь собственную батарею Рэтчета в пустое гнездо.',
    repair_step1: 'Подключи янтарный плюсовой провод к клемме +.',
    repair_step2: 'Подключи синий провод заземления к клемме −.',
    repair_step3: 'Положи перемычку на реле.',
    repair_step4: 'Цепь замкнута. Подай питание, когда будешь готова.',
    repair_retry: 'Это гнездо не подходит. Попробуй подсвеченную деталь ещё раз.',
    repair_boot: 'Подаю питание…',
    op_r1: '…Моя собственная батарея. Ты вернула её на место. Спасибо, малышка, — я Рэтчет.',
    op_r2: 'Песнь Матери заражена. Этот мрамор на моём ожерелье замедлил вирус. Остановить его он не смог.',
    op_r3: 'Поэтому я вынул батарею, пока вирус не взял меня. А ты спала в зарядной колыбели — ты просто не слышала той передачи.',
    op_r4: 'Под лугом лежит большая залежь сырого мрамора. Принеси мне кусок, и я выкую белый меч, который вырезает вирус.',
    op_r5: 'И ещё: эта запасная энергоячейка не для тебя. Она для Старого Серво на лугу. Он тоже выключил себя сам. Разбуди его.',
    op_spare: 'Запасная энергоячейка',
    op_spared: 'Запас Рэтчета — для Старого Серво, смотрителя лебёдки на лугу. Вставь её в него, чтобы разбудить.',
    op_r_pod: 'Эта капсула сохраняет твой прогресс и заряжает тебя. Воспользуйся ею, прежде чем уйти.',
    op_saved: 'Прогресс сохранён · заряд восстановлен',
    op_saved_h: 'Если упадёшь, очнёшься здесь.',
    op_p1: 'Кольцо заряда на тебе наполняется, когда твои удары попадают. Но сейчас тебе его не на что тратить.',
    op_p2: 'Мой вольт-пак это исправит. С ним держи {HEAL}, чтобы починить ядро, или держи {ATK} и отпусти — будет Вольт-взрыв.',
    op_p3: 'Взрыв тебе понадобится: одними когтями сырой мрамор не расколоть. Пак останется твоим навсегда. Стоит 12 лома.',
    op_p4: 'Лома у тебя нет, так что вот 12 — за то, что починила меня. Лом здесь вместо денег: сломанные машины оставляют его после себя.',
    op_scrap: '12 лома',
    op_scrapd: 'Здешние деньги. Сломанные машины оставляют его после себя; Рэтчет берёт его за детали и улучшения.',
    op_s_tag: 'КУПИ СНАЧАЛА ЭТО',
    op_s_pack: 'Вольт-пак · навсегда',
    op_s_packd: 'Подключает к тебе лечение и Вольт-взрыв. Покупается один раз и остаётся твоим.',
    op_s_refill: 'Вольт-заправка', op_s_refilld: 'Полностью восстанавливает вольты.',
    op_s_later: 'После вольт-пака.',
    s_cell: 'Вольт-заправка', s_celld: 'Полностью восстанавливает вольты.',
    i_pack: 'Вольт-пак (навсегда)',
    i_packd: 'Зарядник Рэтчета, подключённый к тебе навсегда. Держи {HEAL}, чтобы тратить вольты на починку ядра. Держи {ATK} и отпусти, чтобы потратить их на Вольт-взрыв.',
    story_pack_first: 'Сначала купи вольт-пак.',
    op_r_heal: 'Первый разряд всегда кусается. Стой спокойно и держи {HEAL} — пак всё починит.',
    op_r_winch: 'Дворовая лебёдка снаружи с самой Песни заклинила поперёк дороги. Иди и останови её — удар, потом взрыв.',
    op_r_node: 'Сразу за лебёдкой стоит монумент с головоломкой. Здесь, внизу, думать выгодно.',
    op_r_go: 'Луг на востоке. Сначала Старый Серво — потом мрамор.',
    op_winch_down: 'Лебёдка вздрагивает и замирает.',
    op_sv_dark: 'Старый Серво темнеет в своём барабане лебёдки. Он выключен — его разбудит энергоячейка.',
    op_sv_seat: 'Запасная ячейка Рэтчета подходит к разъёму в его груди. Ты вставляешь её.',
    op_sv_woke: 'Старый Серво очнулся.',
    op_sv1: 'Мрр… питание! Рабочий блок — да ещё и кошка. Я Старый Серво, смотритель этой лебёдочной. Передай Рэтчету спасибо.',
    op_sv2: 'Ищешь его мрамор? Он под нами. В узле к востоку отсюда, у западного края, шаткий пол — пробей его, и откроются пещеры.',
    op_sv3: 'И просьба, если ноги позволят: катушка с моей эстакады слетела где-то наверху, среди эстакад. Подъём начинается прямо за мной. Принеси её — заплачу 60 лома и 10 IQ.',
    op_sv_cue_dark: 'Выключен · нужна энергоячейка',
    op_sv_cue_wake: '{INT} — разбудить Старого Серво',
    q_where_servo_coil: 'Катушка наверху, среди эстакад — подъём начинается прямо за мной.',
    q_thanks_servo_coil: 'Это моя катушка! Слышишь — барабан снова крутится ровно. Держи: 60 лома и 10 IQ, как обещал.',
    d_servo: [
      'Слышишь? Барабан крутится ровно. Каждая эстакада над лугом снова висит прямо.',
      'Осторожнее с шатким полом в узле, лапка. Это путь вниз, к мрамору.'
    ],
    op_o_gate: 'Дойди до ворот города',
    op_o_booth: 'Найди того, кто ещё не спит, — будка Рэтчета',
    op_o_wake: 'Разбуди Рэтчета',
    op_o_pod: 'Воспользуйся капсулой Рэтчета',
    op_o_pack: 'Получи вольт-пак у Рэтчета',
    op_o_lessons: 'Опробуй вольт-пак',
    op_o_node: 'Реши головоломку монумента',
    op_o_meadow: 'Иди на восток, к Лугам Лома',
    op_o_marble: 'Найди сырой мрамор под лугом',
    op_o_return: 'Отнеси сырой мрамор Рэтчету',
    op_o_sage: 'Освободи первого мудреца — дверь возле мраморного карьера',
    op_o_chime: 'Заставь замолчать колокол на подъёме над лугом',
    op_o_lion: 'Освободи NULLFANG в его загоне за лагерем',
    op_o_conduits: 'Поднимись к Каналам Данных над лагерем',
  },
});
// The interact labels name the player's own control in BOTH worlds: the
// literal "E — Talk" told a pad or phone player to press a key they do not have.
TEXT_LAYERS.push({
  robo: false,
  en: { talk: '{INT} — Talk', rest: '{INT} — Rest', open: '{INT} — Open', read: '{INT} — Read', rd_hint: '{INT} — Solve' },
  ar: { talk: '{INT} — تحدّثي', rest: '{INT} — استريحي', open: '{INT} — افتحي', read: '{INT} — اقرئي', rd_hint: '{INT} — حُلّي اللغز' },
  tr: { talk: '{INT} — Konuş', rest: '{INT} — Dinlen', open: '{INT} — Aç', read: '{INT} — Oku', rd_hint: '{INT} — Çöz' },
  zh: { talk: '{INT} — 交谈', rest: '{INT} — 休息', open: '{INT} — 打开', read: '{INT} — 阅读', rd_hint: '{INT} — 解答' },
  ru: { talk: '{INT} — Говорить', rest: '{INT} — Отдых', open: '{INT} — Открыть', read: '{INT} — Читать', rd_hint: '{INT} — Решить' },
});
