// THE MANHWA'S WORDS — every string the story-panel player (js/panels.js)
// shows, in all five languages. Captions are the approved pages' own lettering
// (assets/source/manhua/ch1/prompts.json) where that lettering still matches
// the game; where the page's words were superseded, the caption is the line
// the game itself now says (noted per key). The teaser lines hint at chapter
// two's place and threat and never at how it ends.
TEXT_LAYERS.push({
  robo: true,
  en: {
    pn_menu: 'Story panels',
    pn_none: 'No story panels yet. They are kept here once you have seen them.',
    pn_hint: 'Enter — replay    Esc — back',
    pn_next: '%s — next',
    pn_skip: 'hold %s to skip',
    pn_next_touch: 'tap — next',
    pn_skip_touch: 'hold the screen to skip',
    pn_s_bay: 'The service bay', pn_s_gate: 'The city gate', pn_s_ratchet: "Ratchet's battery",
    pn_s_cave: 'The marble cave', pn_s_forge: 'The forging', pn_s_meet: 'The corridor',
    pn_s_sage: 'The Meadow Sage', pn_s_chime: 'CHIME', pn_s_free: 'NULLFANG, free',
    pn_s_ch2: 'Next: the Data Conduits',
    // p04 / p05 lettering
    pc_quiet: '...quiet.',
    pc_door: 'The door had been open a long time.',
    pc_city: 'The city was standing. It was silent.',
    pc_gates: 'The gates were the only monument in the kingdom, and nobody had walked through them in a long time.',
    pc_closed: 'They closed behind her. Waking up is one-way too.',
    // p07 lettering; the two lines after it are the game's own (sl_rfrag4 /
    // sl_rfrag1, Oct 4 revision) because p09's balloons were superseded
    pc_awake: 'Ratchet was awake.',
    pc_necklace: 'The marble in my necklace was an old gift to my ancestor. It slowed the virus long enough for me to think. It could not stop the infection.',
    pc_song: "Mother's song kept the robots of every kingdom in harmony. Someone unknown hacked its frequency and hid a virus inside it.",
    // p15 lettering (also the game's rub_open)
    pc_breathing: 'The rock gave way. The tunnel was open, and it was breathing.',
    // the forge: the game's own words (Draft 2 q_thanks, Oct 4 i_crystald);
    // p18's balloons name a "pillar shard" the game no longer has
    pc_forge: 'You brought the marble. Steady the clamp. I will shape the edge, then fit the grip. Cut what is holding them — not what is left of them.',
    pc_blade: 'Ratchet forged a glowing white sword from the cave marble. It frees infected robots — and its handle can later connect to another weapon.',
    // p25 / p26 lettering (p26's two are also the game's sg_tamedd / sg_t_GA1Dd)
    pc_knelt: 'The sage knelt. The song held its body together. Broken, but not CLEAN.',
    pc_cuts: 'Claws could not cleanse the song. The PURIFIER could.',
    pc_letgo: 'The song let go. The sage remembered everything — and gave what it had kept for whoever would come with clean light.',
    pc_cell: 'It had counted every machine that fell in the scrap fields — and kept one power cell safe for whoever came with clean light.',
    // p20 lettering
    pc_singing: 'It was singing at her.',
    pc_nobody: 'Destroyed. There was nobody in it.',
    pc_made: 'A guardian is a machine that was infected. This was not. It had been MADE by the source of the Song, and there was nothing under the virus to give back.',
    // p14 / p24 lettering
    pc_core: 'It took one core. Never her last.',
    pc_bored: 'She was nothing to it. It got bored of her.',
    pc_oath: 'The virus was destroyed. NULLFANG was free. He seemed to like her, and once in every room the blow that would have broken her came out of the dark and roared them off her instead.',
    // the chapter-two teaser
    pt_behind: 'The Scrap Meadows are behind her. The Data Conduits are not.',
    pt_keeper: 'Somewhere in the cables, a keeper of routes is waiting for one clean message.',
    pt_talons: 'And above the dark lines, iron talons are waiting too.',
    // the panels made for the game's own chapter one (2026-10-10)
    pn_s_marble: 'The raw marble', pn_s_passage: 'The maintenance door', pn_s_break: 'NULLFANG resists',
    pc_letter: 'A tag on his chest, in his own hand: his battery was in the drawer.',
    pc_drawer: 'His own battery, exactly where he had left it.',
    pc_m_burst: 'Claws glanced off it. The charge the pack gave her did not.',
    pc_m_freed: 'Raw marble — rounded, unfinished. Not a blade yet. Ratchet would make it one.',
    pc_p_door: 'Beside the stump she had cut, a door opened that had stayed shut for everyone else.',
    pc_p_tunnel: 'The survivors had carried a sage down here once, and sealed it in.',
    pc_s_point: 'It pointed up, toward the climb above the meadow.',
    pc_s_bell: 'NULLFANG is still resisting. But CHIME writes the command back whenever he breaks it.',   // the game's own sg_rev3
    pc_b_stop: 'The purple went out of him. Nothing was driving him.',
    pc_b_bell: 'Then a bell answered from above the meadow, and the order was written back into him.',
    pc_f_cut: 'One clean cut. The virus came off him like ash — and he was still there.',
    pt_hatch: 'The hatch above the camp stood open. Ratchet stayed. NULLFANG watched her go.',
    pt_title: 'CHAPTER TWO — THE DATA CONDUITS',
  },
  ar: {
    pn_menu: 'لوحات القصة',
    pn_none: 'لا لوحات قصة بعد. تُحفظ هنا بعد أن تشاهدها.',
    pn_hint: 'إدخال — إعادة    خروج — رجوع',
    pn_next: '%s — التالي',
    pn_skip: 'استمر بضغط %s للتخطي',
    pn_next_touch: 'انقر — التالي',
    pn_skip_touch: 'استمر بلمس الشاشة للتخطي',
    pn_s_bay: 'حجرة الصيانة', pn_s_gate: 'بوابة المدينة', pn_s_ratchet: 'بطارية راتشيت',
    pn_s_cave: 'كهف الرخام', pn_s_forge: 'الصهر', pn_s_meet: 'الممر',
    pn_s_sage: 'حكيم المروج', pn_s_chime: 'رنين', pn_s_free: 'ناب العدم حرًّا',
    pn_s_ch2: 'التالي: قنوات البيانات',
    pc_quiet: '...هدوء.',
    pc_door: 'كان الباب مفتوحًا منذ زمن طويل.',
    pc_city: 'كانت المدينة قائمة. وكانت صامتة.',
    pc_gates: 'كانت البوابتان النُّصب الوحيد في المملكة، ولم يعبرهما أحد منذ زمن طويل.',
    pc_closed: 'أُغلقتا خلفها. الاستيقاظ أيضًا طريق باتجاه واحد.',
    pc_awake: 'استيقظ راتشيت.',
    pc_necklace: 'كانت قطعة الرخام في قلادتي هدية قديمة لجدّي. أبطأت الفيروس بما يكفي لأفكّر. لكنها لم تستطع إيقاف العدوى.',
    pc_song: 'كانت أغنية الأم تُبقي آليّي كل الممالك في وئام. اخترق مجهولٌ تردّدها وأخفى فيه فيروسًا.',
    pc_breathing: 'انهارت الصخرة. انفتح النفق، وكان يتنفّس.',
    pc_forge: 'أحضرت الرخام. ثبّت المشبك؛ سأشكّل النصل ثم أركّب المقبض. اقطع ما يقيّدهم — لا ما بقي منهم.',
    pc_blade: 'صهر راتشيت من رخام الكهف سيفًا أبيض متوهّجًا. إنه يحرّر الآليين المصابين — ومقبضه يمكن أن يتّصل لاحقًا بسلاح آخر.',
    pc_knelt: 'جثا الحكيم. كانت الأغنية تمسك جسده. محطّمًا، لكن غير نظيف.',
    pc_cuts: 'لم تستطع المخالب تطهير الأغنية. أمّا المُطهّر فاستطاع.',
    pc_letgo: 'أفلتت الأغنية. تذكّر الحكيم كل شيء — وأعطى ما احتفظ به لمن يأتي بالضوء النظيف.',
    pc_cell: 'كان قد أحصى كل آلة سقطت في حقول الخردة — واحتفظ بخلية طاقة واحدة سالمة لمن يأتي بالضوء النظيف.',
    pc_singing: 'كان يغنّي لها.',
    pc_nobody: 'تحطّم. لم يكن فيه أحد.',
    pc_made: 'الحارس آلةٌ أُصيبت بالعدوى. أمّا هذا فلا. لقد صنعه مصدرُ الأغنية، ولم يكن تحت الفيروس شيء يُعاد.',
    pc_core: 'أخذ نواةً واحدة. ولم يأخذ أبدًا آخر نواة لها.',
    pc_bored: 'لم تكن شيئًا في نظره. ملَّ منها.',
    pc_oath: 'تحطّم الفيروس. صار ناب العدم حرًّا. بدا أنه أحبّها، وفي كل غرفة مرّة، كانت الضربة التي كانت ستكسرها تُقابَل بزئير يخرج من الظلام ويطرد مهاجميها.',
    pt_behind: 'مروج الخردة خلفها الآن. أما قنوات البيانات فلا.',
    pt_keeper: 'في مكانٍ ما بين الكوابل، حارسُ طرقٍ ينتظر رسالةً نظيفة واحدة.',
    pt_talons: 'وفوق الخطوط المظلمة، مخالب من حديد تنتظر هي أيضًا.',
    pn_s_marble: 'الرخام الخام', pn_s_passage: 'باب الصيانة', pn_s_break: 'ناب العدم يقاوم',
    pc_letter: 'بطاقة على صدره، بخط يده: بطاريته في الدُرج.',
    pc_drawer: 'بطاريته هو، حيث تركها تمامًا.',
    pc_m_burst: 'انزلقت المخالب عنه. أما الشحنة التي منحتها إياها الحقيبة فلم تنزلق.',
    pc_m_freed: 'رخام خام — مستدير، غير مكتمل. ليس نصلًا بعد. راتشيت سيجعله نصلًا.',
    pc_p_door: 'بجانب الجذع الذي قطعته، انفتح باب ظلّ مغلقًا أمام الجميع.',
    pc_p_tunnel: 'حمل الناجون حكيمًا إلى هنا ذات يوم، ثم أغلقوا عليه.',
    pc_s_point: 'أشار إلى الأعلى، نحو المرتقى فوق المرج.',
    pc_s_bell: 'ناب العدم ما زال يقاوم. لكن رنين يعيد كتابة الأمر فيه كلما كسره.',
    pc_b_stop: 'انطفأ البنفسجي فيه. لم يكن شيء يسوقه.',
    pc_b_bell: 'ثم ردّ جرسٌ من فوق المرج، فكُتب الأمر فيه من جديد.',
    pc_f_cut: 'ضربة نظيفة واحدة. تساقط الفيروس عنه كالرماد — وبقي هو.',
    pt_hatch: 'كانت الكُوّة فوق المخيم مفتوحة. بقي راتشيت. وراقبها ناب العدم وهي تمضي.',
    pt_title: 'الفصل الثاني — قنوات البيانات',
  },
  tr: {
    pn_menu: 'Hikâye panelleri',
    pn_none: 'Henüz hikâye paneli yok. Gördüklerin burada saklanır.',
    pn_hint: 'Enter — yeniden izle    Esc — geri',
    pn_next: '%s — sonraki',
    pn_skip: 'atlamak için %s basılı tut',
    pn_next_touch: 'dokun — sonraki',
    pn_skip_touch: 'atlamak için ekrana basılı tut',
    pn_s_bay: 'Bakım bölmesi', pn_s_gate: 'Şehir kapısı', pn_s_ratchet: "Ratchet'ın pili",
    pn_s_cave: 'Mermer mağara', pn_s_forge: 'Dövme', pn_s_meet: 'Koridor',
    pn_s_sage: 'Çayır Bilgesi', pn_s_chime: 'ÇAN', pn_s_free: 'NULLFANG, özgür',
    pn_s_ch2: 'Sırada: Veri Kanalları',
    pc_quiet: '...sessiz.',
    pc_door: 'Kapı uzun zamandır açıktı.',
    pc_city: 'Şehir ayaktaydı. Sessizdi.',
    pc_gates: 'Kapılar krallıktaki tek anıttı ve uzun zamandır kimse onlardan geçmemişti.',
    pc_closed: 'Arkasından kapandılar. Uyanmak da tek yönlüdür.',
    pc_awake: 'Ratchet uyanmıştı.',
    pc_necklace: 'Kolyemdeki mermer, ataya verilmiş eski bir hediyeydi. Virüsü düşünebileceğim kadar yavaşlattı. Enfeksiyonu durduramadı.',
    pc_song: 'Annenin şarkısı her krallığın robotlarını uyum içinde tutardı. Bilinmeyen biri frekansını ele geçirdi ve içine bir virüs sakladı.',
    pc_breathing: 'Kaya çöktü. Tünel açılmıştı ve nefes alıyordu.',
    pc_forge: 'Mermeri getirdin. Mengeneyi sabit tut. Ağzı ben şekillendireceğim, sonra kabzayı takacağım. Onları bağlayanı kes — onlardan geriye kalanı değil.',
    pc_blade: 'Ratchet mağara mermerinden parlayan beyaz bir kılıç dövdü. Enfekte robotları özgür bırakır — ve kabzası ileride başka bir silaha bağlanabilir.',
    pc_knelt: 'Bilge diz çöktü. Şarkı bedenini bir arada tutuyordu. Kırık, ama TEMİZ değil.',
    pc_cuts: 'Pençeler şarkıyı temizleyemezdi. ARINDIRICI temizleyebilirdi.',
    pc_letgo: 'Şarkı bıraktı. Bilge her şeyi hatırladı — ve sakladığını temiz ışıkla gelecek olana verdi.',
    pc_cell: 'Hurda tarlalarında düşen her makineyi saymıştı — ve temiz ışıkla gelecek olan için bir güç hücresini güvende tutmuştu.',
    pc_singing: 'Ona şarkı söylüyordu.',
    pc_nobody: 'Yok edildi. İçinde kimse yoktu.',
    pc_made: 'Bir muhafız, enfekte olmuş bir makinedir. Bu değildi. Şarkının kaynağı tarafından YAPILMIŞTI ve virüsün altında geri verilecek hiçbir şey yoktu.',
    pc_core: 'Bir çekirdeğini aldı. Asla sonuncusunu değil.',
    pc_bored: 'Onun için hiçbir şeydi. Ondan sıkıldı.',
    pc_oath: 'Virüs yok edildi. NULLFANG özgürdü. Ondan hoşlanmış gibiydi; her odada bir kez, onu kıracak darbe karanlıktan çıkan bir kükremeyle savuşturuldu.',
    pt_behind: 'Hurda Çayırları artık arkasında. Veri Kanalları değil.',
    pt_keeper: 'Kabloların bir yerinde, yolların bekçisi tek bir temiz mesajı bekliyor.',
    pt_talons: 'Ve karanlık hatların üstünde, demir pençeler de bekliyor.',
    pn_s_marble: 'Ham mermer', pn_s_passage: 'Bakım kapısı', pn_s_break: 'NULLFANG direniyor',
    pc_letter: 'Göğsünde kendi el yazısıyla bir etiket: pili çekmecedeydi.',
    pc_drawer: 'Kendi pili, tam bıraktığı yerde.',
    pc_m_burst: 'Pençeler üstünden kaydı. Paketin ona verdiği yük kaymadı.',
    pc_m_freed: 'Ham mermer — yuvarlak, bitmemiş. Henüz bir bıçak değil. Ratchet onu bıçak yapacaktı.',
    pc_p_door: 'Kestiği kütüğün yanında, herkese kapalı kalmış bir kapı açıldı.',
    pc_p_tunnel: 'Hayatta kalanlar bir zamanlar bir bilgeyi buraya taşımış ve içeri kapatmıştı.',
    pc_s_point: 'Yukarıyı, çayırın üstündeki tırmanışı gösterdi.',
    pc_s_bell: 'NULLFANG hâlâ direniyor. Ama ÇAN, o emri her kırdığında komutu yeniden yazıyor.',
    pc_b_stop: 'Mor rengi söndü. Onu süren hiçbir şey yoktu.',
    pc_b_bell: 'Sonra çayırın yukarısından bir çan cevap verdi ve emir ona yeniden yazıldı.',
    pc_f_cut: 'Tek temiz bir kesik. Virüs kül gibi döküldü — ve o hâlâ oradaydı.',
    pt_hatch: 'Kampın üstündeki kapak açıktı. Ratchet kaldı. NULLFANG onun gidişini izledi.',
    pt_title: 'İKİNCİ BÖLÜM — VERİ KANALLARI',
  },
  zh: {
    pn_menu: '故事分镜',
    pn_none: '还没有故事分镜。看过的分镜会保存在这里。',
    pn_hint: 'Enter — 重看    Esc — 返回',
    pn_next: '%s — 下一格',
    pn_skip: '按住 %s 跳过',
    pn_next_touch: '轻触 — 下一格',
    pn_skip_touch: '按住屏幕跳过',
    pn_s_bay: '维修舱', pn_s_gate: '城门', pn_s_ratchet: '拉切特的电池',
    pn_s_cave: '大理石洞穴', pn_s_forge: '锻造', pn_s_meet: '走廊',
    pn_s_sage: '原野贤者', pn_s_chime: '风铃', pn_s_free: '自由的 NULLFANG',
    pn_s_ch2: '下一章：数据回廊',
    pc_quiet: '……好安静。',
    pc_door: '那扇门已经开了很久。',
    pc_city: '城市还矗立着。一片寂静。',
    pc_gates: '这对城门是王国里唯一的纪念碑，已经很久没有人从中走过。',
    pc_closed: '城门在她身后合上。醒来，也是一条单行道。',
    pc_awake: '拉切特醒了。',
    pc_necklace: '我项链里的大理石，是先祖得到的一件古老礼物。它把病毒拖慢到足够让我思考，却挡不住感染。',
    pc_song: '母亲之歌曾让每个王国的机器人和睦相处。一个不知名的人入侵了它的频率，把病毒藏在其中。',
    pc_breathing: '岩石塌开了。隧道敞开着，它在呼吸。',
    pc_forge: '你把大理石带来了。扶稳夹钳。我来打出刃口，再装上握柄。斩断束缚他们的东西——而不是他们仅存的部分。',
    pc_blade: '拉切特用洞穴里的大理石锻出一把发光的白剑。它能解放被感染的机器人——剑柄日后还能与另一件武器相连。',
    pc_knelt: '贤者跪着。歌声把它的身体拼在一起。破碎，却并不干净。',
    pc_cuts: '爪子无法净化歌声。净化者可以。',
    pc_letgo: '歌声松开了。贤者想起了一切——并把它守护的东西交给带着纯净之光而来的人。',
    pc_cell: '它数过废料原野里倒下的每一台机器——并为带着纯净之光而来的人保管了一枚能量电池。',
    pc_singing: '它在对她歌唱。',
    pc_nobody: '被摧毁了。里面没有任何人。',
    pc_made: '守护者是被感染的机器。这个不是。它是歌声的源头亲手造出来的，病毒之下没有任何可以归还的东西。',
    pc_core: '它夺走了一枚核心。从不是最后一枚。',
    pc_bored: '她对它来说什么都不是。它对她失去了兴趣。',
    pc_oath: '病毒被摧毁了。NULLFANG 自由了。他似乎喜欢她：每个房间里有一次，那本会击垮她的一击，会被黑暗中冲出的咆哮挡开。',
    pt_behind: '废料原野已在身后。数据回廊还在前方。',
    pt_keeper: '在电缆深处的某个地方，一位守路人正在等待一条干净的讯息。',
    pt_talons: '而在黑暗的线路之上，铁爪也在等待。',
    pn_s_marble: '原石大理石', pn_s_passage: '检修门', pn_s_break: 'NULLFANG的抗拒',
    pc_letter: '他胸前挂着一张亲笔写的标签：电池在抽屉里。',
    pc_drawer: '他自己的电池，就在他放下的地方。',
    pc_m_burst: '爪子从它上面滑开了。背包给她的那股电荷却没有。',
    pc_m_freed: '原石大理石——圆润，未经打磨。还不是剑刃。拉切特会把它变成剑。',
    pc_p_door: '在她斩断的石桩旁，一扇对别人始终紧闭的门打开了。',
    pc_p_tunnel: '幸存者曾把一位贤者抬到这里，然后把它封在里面。',
    pc_s_point: '它指向上方，指向草原上方的攀登之路。',
    pc_s_bell: 'NULLFANG仍在反抗。可每当他挣断命令，风铃就把它重新写回去。',
    pc_b_stop: '紫光从他身上褪去。没有什么在驱使他。',
    pc_b_bell: '随后，草原上方传来一声钟响，命令又被写回了他的身体。',
    pc_f_cut: '干净的一斩。病毒像灰烬一样从他身上剥落——而他还在。',
    pt_hatch: '营地上方的舱口敞开着。拉切特留了下来。NULLFANG目送她离去。',
    pt_title: '第二章——数据回廊',
  },
  ru: {
    pn_menu: 'Сюжетные панели',
    pn_none: 'Сюжетных панелей пока нет. Увиденные сохраняются здесь.',
    pn_hint: 'Enter — пересмотреть    Esc — назад',
    pn_next: '%s — дальше',
    pn_skip: 'удерживай %s, чтобы пропустить',
    pn_next_touch: 'коснись — дальше',
    pn_skip_touch: 'удерживай экран, чтобы пропустить',
    pn_s_bay: 'Сервисный отсек', pn_s_gate: 'Городские ворота', pn_s_ratchet: 'Батарея Рэтчета',
    pn_s_cave: 'Мраморная пещера', pn_s_forge: 'Ковка', pn_s_meet: 'Коридор',
    pn_s_sage: 'Мудрец Лугов', pn_s_chime: 'КОЛОКОЛ', pn_s_free: 'NULLFANG свободен',
    pn_s_ch2: 'Дальше: Каналы Данных',
    pc_quiet: '...тихо.',
    pc_door: 'Дверь была открыта уже давно.',
    pc_city: 'Город стоял. Он молчал.',
    pc_gates: 'Ворота были единственным памятником королевства, и через них давно никто не проходил.',
    pc_closed: 'Они закрылись за ней. Пробуждение — тоже дорога в одну сторону.',
    pc_awake: 'Рэтчет проснулся.',
    pc_necklace: 'Мрамор в моём ожерелье — старый подарок моему предку. Он замедлил вирус, и я успел подумать. Остановить заражение он не мог.',
    pc_song: 'Песня Матери хранила мир между роботами всех королевств. Кто-то неизвестный взломал её частоту и спрятал в ней вирус.',
    pc_breathing: 'Камень поддался. Туннель был открыт, и он дышал.',
    pc_forge: 'Ты принесла мрамор. Держи зажим ровно. Я выкую лезвие, потом насажу рукоять. Режь то, что держит их, — а не то, что от них осталось.',
    pc_blade: 'Рэтчет выковал из пещерного мрамора светящийся белый меч. Он освобождает заражённых роботов — а его рукоять позже можно соединить с другим оружием.',
    pc_knelt: 'Мудрец стоял на коленях. Песня держала его тело целым. Сломанным, но не ЧИСТЫМ.',
    pc_cuts: 'Когти не могли очистить песню. ОЧИСТИТЕЛЬ мог.',
    pc_letgo: 'Песня отпустила. Мудрец вспомнил всё — и отдал то, что хранил для того, кто придёт с чистым светом.',
    pc_cell: 'Он считал каждую машину, павшую на полях лома, — и сберёг одну энергоячейку для того, кто придёт с чистым светом.',
    pc_singing: 'Оно пело ей.',
    pc_nobody: 'Уничтожено. Внутри никого не было.',
    pc_made: 'Страж — это машина, которую заразили. Это — нет. Его СОЗДАЛ источник Песни, и под вирусом не было ничего, что можно вернуть.',
    pc_core: 'Он забрал одно ядро. Никогда — последнее.',
    pc_bored: 'Она была для него ничем. Ему стало скучно.',
    pc_oath: 'Вирус уничтожен. NULLFANG был свободен. Похоже, она ему понравилась: раз в каждой комнате удар, который сломал бы её, встречал рёв из темноты и отбрасывал врагов.',
    pt_behind: 'Луга Лома позади. Каналы Данных — ещё нет.',
    pt_keeper: 'Где-то в кабелях хранитель маршрутов ждёт одного чистого сообщения.',
    pt_talons: 'А над тёмными линиями ждут и железные когти.',
    pn_s_marble: 'Сырой мрамор', pn_s_passage: 'Служебная дверь', pn_s_break: 'NULLFANG сопротивляется',
    pc_letter: 'На груди — бирка, написанная его рукой: батарея в ящике.',
    pc_drawer: 'Его собственная батарея, ровно там, где он её оставил.',
    pc_m_burst: 'Когти соскользнули. Заряд, который дал ей ранец, — нет.',
    pc_m_freed: 'Сырой мрамор — округлый, необработанный. Это ещё не клинок. Рэтчет сделает его клинком.',
    pc_p_door: 'Рядом с пнём, который она срезала, открылась дверь, запертая для всех остальных.',
    pc_p_tunnel: 'Когда-то выжившие принесли сюда мудреца и замуровали его.',
    pc_s_point: 'Он указал вверх — на подъём над лугом.',
    pc_s_bell: 'NULLFANG всё ещё сопротивляется. Но КОЛОКОЛ записывает приказ обратно каждый раз, когда он его ломает.',
    pc_b_stop: 'Фиолетовый свет в нём погас. Ничто им не управляло.',
    pc_b_bell: 'А потом над лугом отозвался колокол — и приказ записали в него снова.',
    pc_f_cut: 'Один чистый удар. Вирус осыпался с него пеплом — а он остался.',
    pt_hatch: 'Люк над лагерем был открыт. Рэтчет остался. NULLFANG смотрел ей вслед.',
    pt_title: 'ГЛАВА ВТОРАЯ — КАНАЛЫ ДАННЫХ',
  },
});
