// CLAWBYTE — theme layer: one engine, two worlds.
// 'robo' = the Machine Depths (base). 'hero' = the Odyssey (Greek myth —
// ancient public-domain material; all wording here is our own original text).
const PAL_HERO = {
  A: { sky: ['#1a2436', '#2a4a5e'], far: '#3d6273', mid: '#5b8399', solid: '#8a7a5c', dark: '#6b5f45', edge: '#e8d9a8', spike: '#f0e6c8', glow: '#ffd98a', acc2: '#7fd4c8' },
  B: { sky: ['#0a1a30', '#123252'], far: '#1d4a6b', mid: '#2a6485', solid: '#2f5d7a', dark: '#204259', edge: '#8fd8e8', spike: '#c8ecf4', glow: '#5fc8e8', acc2: '#ffd98a' },
  C: { sky: ['#20100a', '#3d1c0e'], far: '#572912', mid: '#743a18', solid: '#6e4a2a', dark: '#4d331d', edge: '#ffb45e', spike: '#ffd9a0', glow: '#ff9838', acc2: '#e8d9a8' },
  D: { sky: ['#16161e', '#26262f'], far: '#3a3a46', mid: '#54545f', solid: '#8f8a80', dark: '#6b675e', edge: '#e8e4d8', spike: '#f8f6ee', glow: '#c8c2f0', acc2: '#8a86d8' },
  E: { sky: ['#140a20', '#26123d'], far: '#3a1f55', mid: '#523575', solid: '#4a3568', dark: '#332348', edge: '#c88ae8', spike: '#e8c2f4', glow: '#b06ae8', acc2: '#7fd4a8' },
  X: { sky: ['#241a08', '#453310'], far: '#6b4d18', mid: '#8f6b24', solid: '#a8842e', dark: '#7a5f20', edge: '#ffe8a0', spike: '#fff4d0', glow: '#ffd75e', acc2: '#e86a5e' },
};
const THEMES = {
  robo: { pal: null, i18n: { en: {}, ar: {} } },
  hero: {
    pal: PAL_HERO,
    i18n: {
      en: {
        z_A: 'Shores of Ithaca', z_B: 'Grotto of Currents', z_C: 'Forge of the Cyclopes',
        z_D: 'Halls of the Dead', z_E: 'Strait of the Sirens', z_X: 'Treasury of the Gods',
        b_glitch: 'The Bronze Boar', b_brood: 'The Siren Mother', b_atlas: 'Talos, the Forge-Giant',
        b_zero: 'The Judge of the Dead', b_prism: 'The Marble Lynx', b_mother: 'Charybdis, the Devourer',
        n_servo: 'Old Mentor', n_ratchet: 'Hermion the Trader', n_mono: 'The Oracle',
        n_sage: 'The Sibyl', n_patch: 'The Tinker of Daedalus', n_lumen: 'A Lost Nymph',
        d_servo: [
          'By the gods… a living soul on this shore! The sea has given something back at last.',
          'Move with the arrows, leap with Z, and let your blade speak with X.',
          'Strike the beasts to gather vigor. Then stand still, hold F — the ✚ mark — and your wounds will close.',
          'A hunger from the deep corrupts every creature it touches. Drive it out, wanderer — or be claimed like the rest.',
          'That windlass behind me hauled our ships ashore, once — I raised half this coast with it, rope by rope. The rope still holds. My knees are what gave.',
        ],
        d_ratchet: [
          'A hero, washed up with empty pockets? Ha! Fortune favors me today. Bronze talks, friend.',
          'Everything I sell was salvaged from ships that no longer needed things.',
          'The stall? Built her from four dead hulls and a festival sail. Everything on this shore is somebody\'s afterwards — mind you don\'t become stock.',
        ],
        d_mono: [
          'I once read the fates of every kingdom. Now I read only ruins.',
          'They say the hunger sings from beneath the Halls of the Dead — a voice the sailors follow down.',
          'Cracked stones hide old passages. Strike them. The gods reward the curious.',
        ],
        intro1: 'The wine-dark sea swallowed your fleet, and the gods went silent.',
        intro2: 'Then a voice beneath the waves began to sing… and sailor after sailor answered it.',
        intro3: 'One wanderer washed ashore still breathing. The oracles had a name for you.',
        intro4: 'STAND UP.',
        rested: 'The altar flame restores you. The gods mark your progress.',
        m_dash: 'Winged Sandals', m_dashd: 'Press C or Shift to surge forward like Hermes.',
        m_djump: 'Gift of the Winds', m_djumpd: 'Leap a second time in mid-air.',
        m_wall: "Climber's Palms", m_walld: 'Cling to cliffs and leap from them.',
        m_emp: "Zeus's Spark", m_empd: 'Press V to hurl a bolt. Costs vigor.',
        m_key: 'Seal of Hades', m_keyd: 'The way below the Halls is open.',
        song_name: 'Lyre of the Wanderer', song_hit: 'Charmed %s',
        ctl_song: 'B — strike the lyre',
        arm_none: 'Bolt', arm_shard: 'BOAR-PLATE — Bronze Volley', arm_jet: 'TIDE-MAIL — Surge',
        arm_slag: 'FORGE-MAIL — Ember Cast', arm_frost: 'SHADE-MAIL — Killing Frost',
        arm_arc: 'MARBLE-MAIL — Zeus\u2019s Lash',
        tt_title: 'Trials of Wisdom', tt_calc: 'Numbers of the Oracle', tt_mem: 'Song of the Sirens',
        tt_vis: 'Stones of the Mason', tt_log: 'Scales of Themis',
        title: 'NOSTOS', subtitle: 'An Odyssey metroidvania — the long way home to Ithaca',
        diff_title: 'Choose Your Fate',
        diff0: 'Lotus-Eater', diff0d: 'Extra hearts, gentler foes. A dreamer’s drift.',
        diff1: 'Wayfarer', diff1d: 'The voyage as the Fates spun it. Fair but firm.',
        diff2: 'Wrath of Poseidon', diff2d: 'Double damage, faster foes — and only nine threads of life.',
        tt_mass: 'Wisdom', rd_title: 'ORACLE STONE',
        sk_title: 'Blessings of the Gods', sk_iq: 'Metis',
        rl_title: 'Treasures', pm_relics: 'Treasures', pm_skills: 'Blessings',
        // ---- blessings of the gods (skill tree) ----
        sk_mind: 'Wisdom of Athena', sk_mindd: '+1 token of favour you may bear.',
        sk_calc: 'Cunning of Odysseus', sk_calcd: 'Your finishing blow strikes 20% harder.',
        sk_reflex: 'Grace of Artemis', sk_reflexd: 'The gods shield you longer after a wound.',
        sk_router: "Hermes' Swiftness", sk_routerd: "Zeus's Spark costs 18 vigour instead of 26.",
        sk_triple: 'Breath of Aeolus', sk_tripled: 'A third leap upon the winds.',
        sk_wave: 'Edge of Achilles', sk_waved: 'Every stroke looses a crescent of force.',
        // ---- treasures of the voyage (relics) ----
        rl_bell: 'Bell of Delphi', rl_belld: 'The slain yield 5% more bronze.',
        rl_lens: 'Eye of the Graeae', rl_lensd: '10% chance a stroke lands twice as hard.',
        rl_coolant: 'Nectar Vial', rl_coolantd: 'Drinking costs 28 vigour instead of 33.',
        rl_spring: 'Feather of Icarus', rl_springd: 'You leap a little higher.',
        rl_fang: 'Boar’s Tusk', rl_fangd: '+8% blade damage. Torn from the Bronze Boar.',
        rl_silk: "Siren's Thread", rl_silkd: '+2 vigour on every hit. Spun by the Siren Mother.',
        rl_ember: 'Cyclops Ember', rl_emberd: 'Blows drive you back only half as far.',
        rl_shard: 'Shard of Styx', rl_shardd: 'You run 4% faster. Cold as the river of the dead.',
        rl_whisker: 'Marble Claw', rl_whiskerd: '+6% blade damage. Still gleaming.',
        rl_silent: 'Heart of Charybdis', rl_silentd: '+1 max heart. The deep is silent now.',
        rl_collar: 'Torc of Ithaca', rl_collard: 'Vigour capacity raised to 110.',
        rl_coin: "Charon's Obol", rl_coind: 'Traders ask 10% less.',
        rl_star: 'Fragment of Orion', rl_stard: 'Treasures are found twice as often.',
        rl_sigil1: 'Seal of the Boar', rl_sigil1d: 'Torn from the Marble Lynx. One of three seals of an old vault.',
        rl_sigil2: 'Seal of the Oracle', rl_sigil2d: 'Earned by answering every Oracle Stone. The second of three.',
        rl_sigil3: 'Seal of the Forge', rl_sigil3d: 'Hidden on a ledge in the Cyclopes’ forge. The last seal.',
        rl_aegis: 'Aegis of Athena', rl_aegisd: 'Turns aside one blow after every rest at a fountain.',
        // ---- tokens of favour (crests) ----
        crest_title: 'Tokens of Favour', crest_slots: 'Bindings', pm_crests: 'Tokens',
        crest_none: 'No tokens yet. Seek chests and traders.',
        c_claws: 'Whetted Xiphos', c_clawsd: '+25% blade damage.',
        c_over: 'Fury of Ares', c_overd: 'Strike 30% faster.',
        c_plate: 'Bronze Cuirass', c_plated: '+1 heart while bound.',
        c_magnet: 'Midas Touch', c_magnetd: 'Bronze flies to you from afar.',
        c_siphon: 'Draught of Dionysus', c_siphond: 'Gain 50% more vigour per hit.',
        c_phantom: 'Helm of Hades', c_phantomd: 'Dashing makes you briefly unseen.',
        c_sprint: 'Sandals of Nike', c_sprintd: 'Run 15% faster and surge further.',
        c_nine: 'Thread of the Fates', c_nined: 'Cheat death once per rest: rise with 3 hearts.',
        s_slot: 'Binding of Favour', s_slotd: 'Permanently bear +1 token.',
        s_core: 'Spare Heart', s_cored: 'Permanently gain +1 max heart.',
        shop_title: "Hermion's Stall",
        evo1: 'THE BRONZE PANOPLY',
        evo1d: 'A hammered bronze breastplate now guards your heart. You stand taller.',
        evo2: 'CLOAK AND SHIELD',
        evo2d: 'A crimson war-cloak flows at your back, a round shield slung beside your blade.',
        evo3: 'FAVORED OF THE GODS',
        evo3d: 'Your panoply turns to gold, a laurel of light crowns your helm, and divine radiance surrounds you.',
      },
      ar: {
        z_A: 'شواطئ إيثاكا', z_B: 'كهف التيارات', z_C: 'مسبك السيكلوب',
        z_D: 'قاعات الموتى', z_E: 'مضيق حوريات البحر', z_X: 'خزانة الآلهة',
        b_glitch: 'الخنزير البرونزي', b_brood: 'أم الحوريات', b_atlas: 'تالوس عملاق المسبك',
        b_zero: 'قاضي الموتى', b_prism: 'وشق الرخام', b_mother: 'كاريبدس المُلتهمة',
        n_servo: 'المرشد العجوز', n_ratchet: 'هرميون التاجر', n_mono: 'العرّافة',
        n_sage: 'الكاهنة', n_patch: 'صانع دايدالوس', n_lumen: 'حورية تائهة',
        d_servo: [
          'بحق الآلهة… روحٌ حيّة على هذا الشاطئ! أعاد البحر شيئًا أخيرًا.',
          'تحرّك بالأسهم، واقفز بـ Z، ودع سيفك يتكلم بـ X.',
          'اضرب الوحوش لتجمع القوة، ثم قف ثابتًا واستمر بالضغط على F — علامة ✚ — وستلتئم جراحك.',
          'جوعٌ من الأعماق يفسد كل مخلوق يلمسه. اطرده أيها التائه — أو تُؤخذ مثل الآخرين.',
          'تلك الرافعة خلفي سحبت سفننا إلى الشاطئ يومًا — رفعتُ نصف هذا الساحل بها، حبلًا حبلًا. الحبل ما زال يشدّ. ركبتاي هما اللتان خانتا.',
        ],
        d_ratchet: [
          'بطلٌ ألقاه البحر بجيوب فارغة؟ ها! الحظ يبتسم لي اليوم. البرونز هو لغة التفاهم يا صديقي.',
          'كل ما أبيعه جُمع من سفنٍ لم تعد تحتاج شيئًا.',
          'المنصّة؟ بنيتُها من أربعة هياكل سفنٍ ميتة وشراعِ مهرجان. كلُّ شيء على هذا الشاطئ هو "ما بعد" أحدهم — فاحذر أن تصير بضاعة.',
        ],
        d_mono: [
          'قرأتُ يومًا مصائر الممالك كلها. والآن لا أقرأ إلا الأطلال.',
          'يقولون إن الجوع يغني من تحت قاعات الموتى — صوتٌ يتبعه البحّارة إلى الأسفل.',
          'الحجارة المتشققة تخفي ممرات قديمة. اضربها. الآلهة تكافئ الفضوليين.',
        ],
        intro1: 'ابتلع البحرُ القاتم أسطولك، وصمتت الآلهة.',
        intro2: 'ثم بدأ صوتٌ تحت الأمواج يغني… فأجابه البحّارة واحدًا تلو الآخر.',
        intro3: 'تائهٌ واحد لفظه البحر وما زال يتنفس. وكان للعرّافات اسمٌ لك.',
        intro4: 'انهض.',
        rested: 'لهيب المذبح يستعيدك. الآلهة تسجّل تقدّمك.',
        m_dash: 'الصندلان المجنّحان', m_dashd: 'اضغط C أو Shift لتندفع كهرمس.',
        m_djump: 'هبة الرياح', m_djumpd: 'اقفز مرة ثانية في الهواء.',
        m_wall: 'كفّا المتسلّق', m_walld: 'تشبّث بالجروف واقفز منها.',
        m_emp: 'شرارة زيوس', m_empd: 'اضغط V لتقذف صاعقة. تكلف قوة.',
        m_key: 'ختم هاديس', m_keyd: 'انفتح الطريق أسفل القاعات.',
        tt_title: 'تجارب الحكمة', tt_calc: 'أرقام العرّافة', tt_mem: 'أغنية الحوريات',
        tt_vis: 'حجارة البنّاء', tt_log: 'ميزان ثيميس',
        title: 'نوستوس', subtitle: 'مغامرة أوديسية — الطريق الطويل إلى إيثاكا',
        diff_title: 'اختر قدرك',
        diff0: 'آكل اللوتس', diff0d: 'قلوب إضافية وأعداء ألطف. انسياب حالم.',
        diff1: 'الرحّالة', diff1d: 'الرحلة كما غزلتها الأقدار. عادلة لكنها صارمة.',
        diff2: 'غضب بوسيدون', diff2d: 'ضعف الضرر، أعداء أسرع — وتسعة خيوط حياة فقط.',
        tt_mass: 'الحكمة', rd_title: 'حجر العرّافة',
        sk_title: 'بركات الآلهة', sk_iq: 'ميتيس',
        rl_title: 'الكنوز', pm_relics: 'الكنوز', pm_skills: 'البركات',
        sk_mind: 'حكمة أثينا', sk_mindd: '+١ رمز حظوة يمكنك حمله.',
        sk_calc: 'دهاء أوديسيوس', sk_calcd: 'ضربتك الأخيرة أقوى بنسبة ٢٠٪.',
        sk_reflex: 'رشاقة أرتميس', sk_reflexd: 'تحميك الآلهة مدةً أطول بعد الإصابة.',
        sk_router: 'سرعة هرمس', sk_routerd: 'شرارة زيوس تكلف ١٨ قوة بدل ٢٦.',
        sk_triple: 'نَفَس إيولوس', sk_tripled: 'قفزة ثالثة على الرياح.',
        sk_wave: 'حدّ أخيل', sk_waved: 'كل ضربة تطلق هلالًا من القوة.',
        rl_bell: 'جرس دلفي', rl_belld: 'يمنحك القتلى ٥٪ برونزًا إضافيًا.',
        rl_lens: 'عين الغرايا', rl_lensd: 'فرصة ١٠٪ أن تصيب الضربة بضعف القوة.',
        rl_coolant: 'قارورة الرحيق', rl_coolantd: 'الشرب يكلف ٢٨ قوة بدل ٣٣.',
        rl_spring: 'ريشة إيكاروس', rl_springd: 'تقفز أعلى قليلًا.',
        rl_fang: 'ناب الخنزير', rl_fangd: '+٨٪ ضرر النصل. انتُزع من الخنزير البرونزي.',
        rl_silk: 'خيط الحورية', rl_silkd: '+٢ قوة مع كل إصابة. غزلته أم الحوريات.',
        rl_ember: 'جمرة السيكلوب', rl_emberd: 'الضربات تدفعك للخلف نصف المسافة فقط.',
        rl_shard: 'شظية ستيكس', rl_shardd: 'تركض أسرع بنسبة ٤٪. باردة كنهر الموتى.',
        rl_whisker: 'مخلب الرخام', rl_whiskerd: '+٦٪ ضرر النصل. ما زال لامعًا.',
        rl_silent: 'قلب كاريبدس', rl_silentd: '+١ قلب أقصى. صار العمق صامتًا.',
        rl_collar: 'طوق إيثاكا', rl_collard: 'ارتفعت سعة القوة إلى ١١٠.',
        rl_coin: 'عملة خارون', rl_coind: 'يطلب التجار أقل بنسبة ١٠٪.',
        rl_star: 'شظية أوريون', rl_stard: 'تُوجد الكنوز بضعف التكرار.',
        rl_sigil1: 'ختم الخنزير', rl_sigil1d: 'انتُزع من وشق الرخام. أحد أختام الخزانة الثلاثة.',
        rl_sigil2: 'ختم العرّافة', rl_sigil2d: 'نلته بالإجابة عن كل حجر عرّافة. الثاني من ثلاثة.',
        rl_sigil3: 'ختم المسبك', rl_sigil3d: 'مخبأ على حافة في مسبك السيكلوب. الختم الأخير.',
        rl_aegis: 'درع أثينا', rl_aegisd: 'يصد ضربة واحدة بعد كل راحة عند النافورة.',
        crest_title: 'رموز الحظوة', crest_slots: 'الأربطة', pm_crests: 'الرموز',
        crest_none: 'لا رموز بعد. ابحث في الصناديق وعند التجار.',
        c_claws: 'سيف مشحوذ', c_clawsd: '+٢٥٪ ضرر النصل.',
        c_over: 'سَورة آريس', c_overd: 'تضرب أسرع بنسبة ٣٠٪.',
        c_plate: 'درع برونزي', c_plated: '+١ قلب أثناء الارتباط.',
        c_magnet: 'لمسة ميداس', c_magnetd: 'يطير البرونز إليك من بعيد.',
        c_siphon: 'شراب ديونيسوس', c_siphond: 'تكسب ٥٠٪ قوة إضافية لكل إصابة.',
        c_phantom: 'خوذة هاديس', c_phantomd: 'الاندفاع يجعلك خفيًّا للحظة.',
        c_sprint: 'صندلا نايكي', c_sprintd: 'تركض أسرع ١٥٪ وتندفع أبعد.',
        c_nine: 'خيط الأقدار', c_nined: 'اخدع الموت مرة كل راحة: تنهض بثلاثة قلوب.',
        s_slot: 'رباط حظوة', s_slotd: 'احمل رمزًا إضافيًا بشكل دائم.',
        s_core: 'قلب احتياطي', s_cored: 'اكسب +١ قلب أقصى بشكل دائم.',
        shop_title: 'كشك هرميون',
        evo1: 'العُدّة البرونزية',
        evo1d: 'درعُ صدرٍ برونزيٌّ مطروق يحرس قلبك الآن. صرتَ أطول قامة.',
        evo2: 'العباءة والترس',
        evo2d: 'عباءةُ حربٍ قرمزية تتموّج خلفك، وترسٌ مستدير معلّق إلى جانب نصلك.',
        evo3: 'محبوبُ الآلهة',
        evo3d: 'تحوّلت عدّتُك إلى ذهب، وتوّج خوذتَك إكليلٌ من نور، وأحاطك إشعاعٌ إلهيّ.',
      },
    },
  },
};
function themeId() {
  // a build can be LOCKED to one game (two separate libraries: the cat's
  // CLAWBYTE page and the hero's NOSTOS page each ship with their own lock)
  const lock = (typeof window !== 'undefined' && window.GAME_LOCK) || null;
  if (typeof G !== 'undefined' && G.state) {
    const s = G.state;
    // the shell (title menu / chooser / language) wears the locked world…
    if (s === 'MENU' || s === 'WHO' || s === 'LANGSEL') return lock || 'robo';
    // …and once a character is chosen, the difficulty screen previews THAT world
    if (s === 'DIFF') return G.pendTheme || lock || 'robo';
  }
  return (typeof G !== 'undefined' && G.save && G.save.theme) || lock || 'robo';
}
function isHero() { return themeId() === 'hero'; }
