// CLAWBYTE build: emits index.html + odyssey.html (and the two Forge pages)
// from dev.html and the js/ sources. Run: node build.cjs
const fs = require('fs');
// The core hero sheets are inlined into the CLAWBYTE page so she is never
// drawn without her body; everything else is fetched (js/media.js).
const heroCore = {};
for (const [key,file] of Object.entries({heroStates:'states.webp', gaitWalk:'gait/walk.webp', gaitRun:'gait/run.webp', hzdIdle:'idle.webp'})) {
  heroCore[key] = 'data:image/webp;base64,' + fs.readFileSync('assets/characters/hero/' + file).toString('base64');
}

// IMPORTANT: production repairs belong in the compiled source order. Keeping
// them outside this list made Pages, desktop and local builds run different
// games. They are now part of BUILD_ID and every target executes the same code.
const comicManifest = require('./tools/validate-comics.cjs')();
const files = require('./source-files.json').map(f => fs.readFileSync('js/' + f + '.js', 'utf8'));
let roomAssets='null'; try{roomAssets=fs.readFileSync('assets/roomassets.json','utf8').trim();}catch(e){}
// where every hostile body's eyes are, per cell of its art (tools/eyemap.cjs) — the infection's eye smoke anchors to it
let eyeMap='{}'; try{eyeMap=fs.readFileSync('assets/eyes.json','utf8').trim();}catch(e){}
let lowres='null'; try{lowres=fs.readFileSync('assets/lowres/index.json','utf8').trim();}catch(e){}
const MUS_EXT=/\.(ogg|mp3|m4a|wav)$/i, musFiles={}; try{for(const f of fs.readdirSync('assets/music').sort()) if(MUS_EXT.test(f)) musFiles[f.replace(MUS_EXT,'')]='assets/music/'+f;}catch(e){}
const VID_EXT=/\.(mp4|webm|mov)$/i, vidFiles={},vidAlt={}; try{for(const f of fs.readdirSync('assets/video').sort()){if(!VID_EXT.test(f))continue;const b=f.replace(VID_EXT,'');if(/\.webm$/i.test(f))vidAlt[b]='assets/video/'+f;else vidFiles[b]='assets/video/'+f;}for(const k in vidAlt)if(!vidFiles[k]){vidFiles[k]=vidAlt[k];delete vidAlt[k];}}catch(e){}
let vidLight='null';try{vidLight=fs.readFileSync('assets/video/light/index.json','utf8').trim();}catch(e){}
const VOX_EXT=/\.(ogg|mp3|m4a|wav)$/i,voxFiles={};try{for(const f of fs.readdirSync('assets/vox').sort())if(VOX_EXT.test(f))voxFiles[f.replace(VOX_EXT,'')]='assets/vox/'+f;}catch(e){}
const html=fs.readFileSync('dev.html','utf8'),loader=fs.readFileSync('loader.html','utf8'),editorJs=fs.readFileSync('js/editor.js','utf8');
const SITE='https://zaferdajani.github.io/HZD-99',STUDIO='VibeSolutions';
function seoBlock(fname,lock,forge){if(forge)return '<meta name="robots" content="noindex,nofollow">\n<meta name="viewport" content="width=device-width,initial-scale=1">';const hero=lock==='hero',url=SITE+(hero?'/odyssey.html':'/'),name=hero?'NOSTOS':'CLAWBYTE',tagline=hero?'An Odyssey metroidvania — the long way home to Ithaca.':'A robo-cat metroidvania in the Machine Depths.',desc=tagline+' A hand-built action game that runs in the browser — no install, no account. Explore, fight guardians, earn skills, and find the way through.',img=SITE+'/assets/social/'+(hero?'nostos':'clawbyte')+'.png',ld=JSON.stringify({'@context':'https://schema.org','@type':'VideoGame',name,description:desc,url,image:img,genre:['Action','Metroidvania','Platformer'],gamePlatform:'Web browser',applicationCategory:'Game',operatingSystem:'Any (modern web browser)',author:{'@type':'Organization',name:STUDIO,url:SITE},publisher:{'@type':'Organization',name:STUDIO,url:SITE},creator:{'@type':'Person',name:'Zafer Dajani'},inLanguage:['en','ar','tr','zh','ru'],offers:{'@type':'Offer',price:'0',priceCurrency:'USD',availability:'https://schema.org/InStock',url}}).replace(/</g,'\\u003c').replace(/>/g,'\\u003e');return ['<meta name="description" content="'+desc+'">','<meta name="author" content="'+STUDIO+'">','<meta name="publisher" content="'+STUDIO+'">','<link rel="canonical" href="'+url+'">','<meta name="robots" content="index,follow">','<meta property="og:type" content="website">','<meta property="og:site_name" content="'+name+'">','<meta property="og:title" content="'+name+' — '+tagline+'">','<meta property="og:description" content="'+desc+'">','<meta property="og:url" content="'+url+'">','<meta property="og:image" content="'+img+'">','<meta property="og:image:width" content="1200">','<meta property="og:image:height" content="630">','<meta property="og:image:alt" content="'+name+' title screen">','<meta name="twitter:card" content="summary_large_image">','<meta name="twitter:title" content="'+name+'">','<meta name="twitter:description" content="'+tagline+'">','<meta name="twitter:image" content="'+img+'">','<meta name="theme-color" content="#04060a">','<script type="application/ld+json">'+ld+'</script>'].join('\n');}
const buildId=require('crypto').createHash('sha256').update(require('./tools/runtime-asset-digest.cjs')()).update(fs.readFileSync('sw.js')).update(fs.readFileSync(__filename)).update(html).update(loader).update(editorJs).update(files.join('\n')).update(JSON.stringify(heroCore)).update(JSON.stringify(musFiles)).update(JSON.stringify(vidFiles)).update(JSON.stringify(vidAlt)).update(String(vidLight)).update(JSON.stringify(voxFiles)).update(String(roomAssets)).update(String(eyeMap)).update(String(lowres)).digest('hex').slice(0,12);
const emit=(fname,lock,forge)=>{let shell=html;if(lock==='hero')shell=shell.replace(/<title>[^<]*<\/title>/,'<title>NOSTOS — an Odyssey metroidvania</title>');if(forge)shell=shell.replace(/<title>[^<]*<\/title>/,'<title>THE FORGE</title>');shell=shell.replace('<!--PCN-SEO-->',seoBlock(fname,lock,forge));const out=shell.replace(/<!-- GAME-SOURCES -->[\s\S]*<\/body>/,()=>'<script>window.GAME_LOCK='+JSON.stringify(lock)+'</script>\n'+loader+'\n<script>window.BUILD_ID='+JSON.stringify(buildId)+(forge?';window.EDITOR=1':'')+';window.COMIC_MANIFEST='+JSON.stringify(comicManifest).replace(/</g,'\\u003c')+';window.EMBEDDED_MEDIA='+JSON.stringify(lock==='robo'?heroCore:{})+';window.GAME_LOCK='+JSON.stringify(lock)+';window.MUS_FILES='+JSON.stringify(musFiles)+';window.VID_FILES='+JSON.stringify(vidFiles)+';window.VID_ALT='+JSON.stringify(vidAlt)+';window.VID_LIGHT='+vidLight+';window.VOX_FILES='+JSON.stringify(voxFiles)+';window.ROOM_ASSETS='+roomAssets+';window.EYE_MAP='+eyeMap+';window.LOWRES='+lowres+'</script>\n<script>\n'+files.join('\n')+(forge?'\n'+editorJs:'')+'\n</script>\n</body>');fs.writeFileSync(fname,out);console.log(fname+' built ('+lock+(forge?'+forge':'')+'):',(fs.statSync(fname).size/1048576).toFixed(2)+'MB');};
emit('index.html','robo');emit('odyssey.html','hero');emit('forge.html','robo',true);emit('forge-odyssey.html','hero',true);
