const fs=require('node:fs');
function edit(file,old,replacement){const text=fs.readFileSync(file,'utf8');if(text.includes(replacement))return;if(text.split(old).length!==2)throw Error('Changed probe baseline: '+file);fs.writeFileSync(file,text.replace(old,replacement));}
edit('tests/wake.cjs',"await steer(s.target!=null && s.target < s.x-8 ? 'ArrowLeft':'ArrowRight');","// An exit marker points THROUGH the seam, not to a spot to turn around at.\n        await steer(['out','go'].includes(s.step) ? 'ArrowRight' : s.target!=null && s.target < s.x-8 ? 'ArrowLeft':'ArrowRight');");
edit('tests/wake.cjs',"const key=[s.room,s.state,s.step,s.action,s.lock].join(':');","const key=[s.room,s.state,s.step,s.action,s.lock,Math.floor(s.x/80)].join(':');");
edit('tests/wake.cjs',"const deadline = Date.now() + 50000;","const deadline = Date.now() + 90000;");
edit('tests/wake.cjs',"lock:G.tutorialLock && G.tutorialLock.action};","lock:G.tutorialLock && G.tutorialLock.action, vx:player.vx, y:player.y, input:!!keys.ArrowRight, suspended:inputSuspended};");
edit('tests/film.cjs',"for (let i = 0; i < 130; i++) {","const reelDeadline=Date.now()+180000;\n  for (let i=0; Date.now()<reelDeadline; i++) {");
const seekStart="    // After witnessing decoded, advancing footage, exercise the real end-of-";
const file='tests/film.cjs';let text=fs.readFileSync(file,'utf8');
if(text.includes(seekStart)){const begin=text.indexOf(seekStart),end=text.indexOf('    await p.waitForTimeout(150);',begin);if(end<0)throw Error('Missing film probe boundary');text=text.slice(0,begin)+"    // Let each clip end naturally. Seeking on an HTTP server without byte-\n    // range support can stall the test even when ordinary playback is healthy.\n"+text.slice(end);fs.writeFileSync(file,text);}
edit('tests/film.cjs',"if (s.st === 'CINE') everFallback = true;","if (s.st === 'CINE') everFallback = true;\n    if(i%20===0) console.log('reel progress',JSON.stringify(s));");
const probe='tests/release-polish.cjs';text=fs.readFileSync(probe,'utf8');
const begin=text.indexOf(' const clips=await page.evaluate(async()=>{'),end=text.indexOf('\n }\n assert.deepEqual(errors,[]);',begin);
const replacement=` // Use the game's connected inline video and its actual codec ordering. The\n // previous probe forced WebM into a display:none element, unlike gameplay.\n await page.mouse.click(8,8);\n const clips=await page.evaluate(async()=>{\n   const r=[];G.reel=null;G.reelEnd=null;G.cutEnd=null;\n   for(let i=1;i<=8;i++){\n     const key='intro'+i;G.state='PLAY';\n     const started=startPurifyCut(key);const ct=G.cut;\n     const stop=Date.now()+16000;\n     while(ct && G.cut===ct && !(ct.ran && ct.v.currentTime>=.08) && Date.now()<stop)\n       await new Promise(resolve=>setTimeout(resolve,30));\n     const v=ct && ct.v;\n     r.push({key,started,time:v?v.currentTime:0,width:v?v.videoWidth:0,ran:!!(ct&&ct.ran),\n       src:v&&v.currentSrc,phase:ct&&ct.ph,error:v&&v.error?{code:v.error.code,message:v.error.message}:null});\n     if(G.cut===ct)endPurifyCut();\n   }return r;\n });\n fs.writeFileSync(out+'/clips-'+(process.env.QA_BROWSER||'chromium')+'.json',JSON.stringify(clips,null,2));\n console.log('Production clip playback',JSON.stringify(clips));\n assert(clips.every(c=>c.started&&c.ran&&c.width>0&&c.time>=.08&&!c.error),'Production movie playback: '+JSON.stringify(clips));\n record('all eight intro clips really decode and advance',clips);`;
if(!text.includes('Production clip playback')){if(begin<0||end<0)throw Error('Unknown movie probe');fs.writeFileSync(probe,text.slice(0,begin)+replacement+text.slice(end));}
console.log('Corrected real-play traversal and production-codec probes');
